### ISSUE TITLE
求新增视频搜索起始和结束时间

### ISSUE THREAD

**Issue by LittleTerry** [chn-lee-yumi/MaterialSearch#1]
感谢作者辛苦开发这款脚本！从B站过来的粉丝～请问能否新增功能：搜索视频后，返回视频的起始和结束时间？

**Comment by chn-lee-yumi** [comment]
感谢支持，后续有时间会增加此功能

**Comment by chn-lee-yumi** [comment]
Hi, 现在该功能已实现，使用最新版代码即可。不过因为数据库做了修改，所以得删库重新扫描一遍~

**Comment by LittleTerry** [comment]
> Hi, 现在该功能已实现，使用最新版代码即可。不过因为数据库做了修改，所以得删库重新扫描一遍~

非常感谢您新增这个功能！辛苦了！我这边测试下。点赞👍

**Comment by LittleTerry** [comment]
反馈：程序能够正常运行，并且能够显示起始和截至时间。感谢！
不过我也注意到一个现象，貌似程序只能扫描到mp4的视频。mkv格式的好像不支持。
无论如何，感谢您新增这个功能。

**Comment by chn-lee-yumi** [comment]
@LittleTerry 你好，刚刚更新了中文支持，直接更新代码就可以用了，不需要重新扫描。

**Comment by LittleTerry** [comment]
> > 貌似程序只能扫描到mp4的视频。mkv格式的好像不支持。
> 
> 你可以修改 https://github.com/chn-lee-yumi/MaterialSearch/blob/main/process_assets.py#L11 增加对应格式。我没有进行过测试，不过应该也是支持的。

谢谢提醒，测试有效👍

**Comment by LittleTerry** [comment]
> @LittleTerry 你好，刚刚更新了中文支持，直接更新代码就可以用了，不需要重新扫描。

感谢！辛苦了💦
