### ISSUE TITLE
这个可以设置默认过滤掉吧

### ISSUE THREAD

**Issue by oiuv** [chn-lee-yumi/MaterialSearch#10]
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/13300261/549bd116-908d-4fb5-bb8d-c953263a2a38)

强迫症看着难受

**Comment by chn-lee-yumi** [comment]
可以，没什么问题。不过我有点好奇为啥你在win下面有mac的文件夹……

**Comment by oiuv** [comment]
> 可以，没什么问题。不过我有点好奇为啥你在win下面有mac的文件夹……

我也奇怪啊，正常应该是从mac复制过来的文件才可能带这个文件夹，但目前这报警告的都是我windows电脑原生的应用啊，可能是这个软件自己的问题。

**Comment by chn-lee-yumi** [comment]
我查了一下路径，好像是抖音直播伴侣附带的……
