### ISSUE TITLE
经过各种测试 搜索显示NEF图片文件，但是点击预览就提示错误，FAILED，希望能修复一下，800G照片都是NEF格式

### ISSUE THREAD

**Issue by KENUNK** [chn-lee-yumi/MaterialSearch#101]
![image](https://github.com/user-attachments/assets/cbccf700-fc54-4e8f-96ef-73af16c43529)
![image](https://github.com/user-attachments/assets/7efe340e-7dab-437c-b73a-44b884898523)
 其他图片格式缩率图显示点击预览也会显示图片，  换电脑和nas 手机上都测试了，只有NEF格式  预览提示错误  如图

**Comment by chn-lee-yumi** [comment]
请见"已知问题"第一条：

> 部分图片和视频无法在网页上显示，原因是浏览器不支持这一类型的文件（例如tiff文件，svq3编码的视频等）。

**Comment by KENUNK** [comment]
不支持？但是搜索出来显示小的图片正常，点击放大就提示错误， 属于浏览器不支持？

**Comment by chn-lee-yumi** [comment]
> 但是搜索出来显示小的图片正常，点击放大就提示错误

小图片是缩略图，大图片是原图，格式不一样。

**Comment by KENUNK** [comment]
明白了，

**Comment by chn-lee-yumi** [comment]
我已更新“已知问题”，让描述变得更加清楚。
