### ISSUE TITLE
安装包出问题是什么原因

### ISSUE THREAD

**Issue by xiaoduoandhana** [chn-lee-yumi/MaterialSearch#102]
OSError: [WinError 126] 找不到指定的模块。 Error loading "D:\work\tools\python3.10.6\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by chn-lee-yumi** [comment]
运行环境问题请自行解决。

**Comment by chn-lee-yumi** [comment]
可以参考：https://github.com/pytorch/pytorch/issues/129568

**Comment by chn-lee-yumi** [comment]
最新版本整合包已修复此问题
