### ISSUE TITLE
希望大佬有时间的时候能实现一个图片去重的算法

### ISSUE THREAD

**Issue by hepra** [chn-lee-yumi/MaterialSearch#103]
在数据库里高效对比相似度>95的图片 然后返回一个列表 用于去删除重复项,
我不知道是否有更高效的算法可以直接在数据库里高效对比
我的实现就最简单的 一个一个对比 
大佬如果有思路,麻烦讲一下关键词

**Comment by chn-lee-yumi** [comment]
你说的去重，是指整个文件完全一样的去重，还是相似图片的去重？

**Comment by hepra** [comment]
相似的 因为有些图可能有水印 导致会有一些差别 不是完全一样的

**Comment by chn-lee-yumi** [comment]
什么情况下会用到这种功能呢？

**Comment by jianhudiyi** [comment]
在一些个人或者企业文档管理中，用于减少冗余数据，能用上

> 什么情况下会用到这种功能呢？

**Comment by jianhudiyi** [comment]
大佬，能否增加一个视频删除按钮，能对查找出来的素材进行删除

**Comment by chn-lee-yumi** [comment]
> 大佬，能否增加一个视频删除按钮，能对查找出来的素材进行删除

不可以用文件管理器删么？

**Comment by jianhudiyi** [comment]
> > 大佬，能否增加一个视频删除按钮，能对查找出来的素材进行删除
> 
> 不可以用文件管理器删么？

用文件管理器删的话，需要复制这个文件的地址，再进行搜索删除，再批量删除的时候，有点麻烦

**Comment by chn-lee-yumi** [comment]
> 用文件管理器删的话，需要复制这个文件的地址，再进行搜索删除，在批量删除的时候，有点麻烦

前端一个个点删除不也麻烦么？

**Comment by hepra** [comment]
在个人或企业素材管理的时候 有很多重复的资源 需要查重减少冗余数据  统计出来之后直接一键清理了

**Comment by jianhudiyi** [comment]
> > 用文件管理器删的话，需要复制这个文件的地址，再进行搜索删除，在批量删除的时候，有点麻烦
> 
> 前端一个个点删除不也麻烦么？

不用频繁切换页面

**Comment by leolulu** [comment]
使用其他第三方软件去重再用这个搜索就好了
专业的事情用专业的对应工具去做
推荐去重用：Duplicate.Cleaner.Pro   
@hepra

**Comment by chn-lee-yumi** [comment]
> 使用其他第三方软件去重再用这个搜索就好了 专业的事情用专业的对应工具去做 推荐去重用：Duplicate.Cleaner.Pro @hepra @jianhudiyi

同意。所以我关闭这个issue了。
