### ISSUE TITLE
nas上开启自动扫描后，会在时间区间不间断重复扫描，扫描结束又会触发继续扫描，

### ISSUE THREAD

**Issue by KENUNK** [chn-lee-yumi/MaterialSearch#104]
能否扫描一遍就自动结束扫描，这样区间不间断重复扫很占用cpu 内存资源

**Comment by chn-lee-yumi** [comment]
这是bug，你的想法是正确的，也是我期望的。我修复一下。

**Comment by chn-lee-yumi** [comment]
我已提交了更新，你可以测试一下是否正常。将`scan.py`替换掉即可。如果没问题，我再重新打新的整合包。

**Comment by KENUNK** [comment]
容器我把这个文件挂载替换了， 测试还是不行，重复触发扫描，扫完一遍又开始重新扫循环

**Comment by KENUNK** [comment]
OK了，整合包，nas 都测了 不会重复扫描了 昨晚代码复制错了一行
