### ISSUE TITLE
能否推出区域搜索功能

### ISSUE THREAD

**Issue by jianhudiyi** [chn-lee-yumi/MaterialSearch#108]
起因是我想搜索视频中的某一些贴纸或者其它元素，我使用截图裁取这部分内容，进行以图搜图，结果不是很理想，所以我想是否能增加一个区域搜索的功能，用于搜索视频的画中画这种，使用一些特定的区域搜索算法或者集成一些识别模型

**Comment by chn-lee-yumi** [comment]
这个并不好实现。
