### ISSUE TITLE
install_torch_gpu.bat的命令错误

### ISSUE THREAD

**Issue by zuiaiyutu** [chn-lee-yumi/MaterialSearch#111]
运行pip install -U torch<2.4 --index-url=https://download.pytorch.org/whl/cu118 命令会出现如下错误
问了一下chatgpt
改成 pip install -U "torch<2.4" --index-url https://download.pytorch.org/whl/cu118 就成功运行了
![语法错误6](https://github.com/user-attachments/assets/e5fdcd1a-d883-4810-9092-97d7057423fa)

**Comment by chn-lee-yumi** [comment]
感谢提醒，已修复。
