### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by zuiaiyutu** [chn-lee-yumi/MaterialSearch#112]
自己克隆到本地的项目，没法正常启动，感觉像是没法下载huggingface上的东西，但是如果把一键包里huggingface文件夹下的所有文件，复制到克隆的项目里，就可以正常启动了。
![启动](https://github.com/user-attachments/assets/f3b028b7-7dfc-4b90-ae9c-be3e49fd56ed)

**Comment by chn-lee-yumi** [comment]
> 注意，首次运行会自动下载模型。下载速度可能比较慢，请耐心等待。如果网络不好，模型可能会下载失败，这个时候重新执行程序即可。

这是正常的，服务器在国外，国内经常连不上。
