### ISSUE TITLE
Windows整合包无法扫描文件夹

### ISSUE THREAD

**Issue by tracyqin07** [chn-lee-yumi/MaterialSearch#116]
测试了下扫描C盘的下载文件夹（有228个文件）是正常的，但是无法扫描另一个硬盘的一个以中文起名的大文件夹。这个文件夹有大量图片，加上视频的话文件夹大小有256g。文件夹属性如下图。、
![QQ截图20240913191942](https://github.com/user-attachments/assets/7ccbed59-7b77-44e9-ab0e-34a68050040d)

扫描时基本数秒就结束，什么都没扫出来。
![QQ截图20240913192223](https://github.com/user-attachments/assets/683acf49-dbf5-4a2d-a0fb-eab42decc581)

请问无法扫描的原因是文件路径不能包含中文，还是说文件数量太多就无法扫描了？

**系统信息如下：**

操作系统名称	Microsoft Windows 10 专业版
版本	10.0.19045 内部版本 19045
其他操作系统描述 	没有资料
操作系统制造商	Microsoft Corporation
系统名称	DESKTOP-VJ9G2R5
系统制造商	MSI
系统型号	MS-7918
系统类型	基于 x64 的电脑
系统 SKU	To be filled by O.E.M.
处理器	Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz，3401 Mhz，4 个内核，8 个逻辑处理器
BIOS 版本/日期	American Megatrends Inc. V2.10, 2016/2/16
SMBIOS 版本	2.8
嵌入式控制器版本	255.255
BIOS 模式	UEFI
主板制造商	MSI
主板产品	Z97 GAMING 3 (MS-7918)
主板版本	1.0
平台角色	台式机
安全启动状态	关闭
PCR7 配置	无法绑定
Windows 目录	C:\Windows
系统目录	C:\Windows\system32
启动设备	\Device\HarddiskVolume1
区域设置	中国
硬件抽象层	版本 = "10.0.19041.3636"
用户名	DESKTOP-VJ9G2R5\tracy
时区	中国标准时间
已安装的物理内存(RAM)	32.0 GB
总的物理内存	31.9 GB
可用物理内存	17.5 GB
总的虚拟内存	54.9 GB
可用虚拟内存	37.6 GB
页面文件空间	23.0 GB
页面文件	E:\pagefile.sys
内核 DMA 保护	关闭
基于虚拟化的安全性	未启用
设备加密支持	设备自动加密失败的原因: TPM 不可用, 不支持 PCR7 绑定, 硬件安全测试界面失败，设备未处于现代待机模式, 检测到不允许使用的具有 DMA 功能的总线/设备, TPM 不可用
Hyper-V - 虚拟机监视模式扩展	是
Hyper-V - 第二级地址转换扩展	是
Hyper-V - 固件中启用的虚拟化	是
Hyper-V - 数据扩展保护	是

**Comment by lynneTest** [comment]
换一个没有中文名的路径试一下能不能扫描

**Comment by tracyqin07** [comment]
> 换一个没有中文名的路径试一下能不能扫描

昨晚试了，有中文名路径的小文件夹（约400个图片，无子文件夹）可以扫描。但大的还是不行。

**Comment by chn-lee-yumi** [comment]
这是因为路径包含空格，你试试把空格转义一下？写成`My\ Document`这样子。

**Comment by tracyqin07** [comment]
> 这是因为路径包含空格，你试试把空格转义一下？写成`My\ Document`这样子。

好的谢谢，我试试。
可以问问路径里还有没有别的禁忌吗？因为我的素材图片的子文件夹会有【】这个大括号和全角斜杠，全角逗号顿号以及空格之类

**Comment by chn-lee-yumi** [comment]
> 可以问问路径里还有没有别的书写禁忌吗？

英文空格、斜杠、引号大概会有问题，别的应该没啥问题。

**Comment by tracyqin07** [comment]
> > 可以问问路径里还有没有别的书写禁忌吗？
> 
> 英文空格、斜杠、引号大概会有问题，别的应该没啥问题。

看来需要找时间逐一修改了 TwT ，谢谢

**Comment by tracyqin07** [comment]
> 这是因为路径包含空格，你试试把空格转义一下？写成`My\ Document`这样子。

你好，我试了试这个转义方式无效呢？

我是这样写的，能帮忙看看哪里错了吗？
ASSETS_PATH=D:\Test/ Files

（因为我不懂写程序，所以跑去问了一下GPT，它的文件路径的斜杆好像跟win的文件浏览器是反的，所以我有点蒙圈了，然后它这里两个转义方法我都没成功）
![QQ截图20240916121111](https://github.com/user-attachments/assets/51cb69b5-6442-4724-b1ca-87d19e9601b8)

打扰了抱歉哈。

**Comment by chn-lee-yumi** [comment]
> 你好，我试了试这个转义方式无效呢？

我没有windows电脑，我也没办法排查呢

**Comment by chn-lee-yumi** [comment]
这个空格的兼容问题后面我看看咋处理吧。

**Comment by shenkunlovecoding** [comment]
具体扫描的实现在哪？

**Comment by chn-lee-yumi** [comment]
最新的版本添加了路径检查，启动后如果发现路径不存在会打印WARNING。你可以用新版本测试一下。
