### ISSUE TITLE
CUDA加速安装.bat 无法下载torch文件

### ISSUE THREAD

**Issue by tracyqin07** [chn-lee-yumi/MaterialSearch#117]
使用的是windows整合包，CUDA加速安装.bat 运行后显示如下错误。
![QQ截图20240916190949](https://github.com/user-attachments/assets/5859cde1-d83b-47b6-93b4-ce3cd6684557)

**Comment by chn-lee-yumi** [comment]
这不是本项目的问题。以下链接希望对你有所帮助：

https://stackoverflow.com/questions/71435874/pip-these-packages-do-not-match-the-hashes-from-the-requirements-file

https://www.bing.com/search?q=these+packages+do+not+match+the+hashes+&qs=n&form=QBRE&sp=-1&ghc=1&lq=0&pq=these+packages+do+not+match+the+hashes+&sc=10-39&sk=&cvid=BD72400D850D4F0986D4B16476F78C1E&ghsh=0&ghacc=0&ghpl=
