### ISSUE TITLE
希望能够升级一下剪辑搜索到的视频片段功能

### ISSUE THREAD

**Issue by gramophone-g** [chn-lee-yumi/MaterialSearch#118]
您好，软件功能非常棒。在大量素材中搜索想要的视频片段很快。不过对于搜索到的视频片段，目前是提供直接剪辑下载的功能。对于这个功能能否再做更进一步的升级：能够对搜索出的视频片段做调整（开始时间、结束时间），调整之后再下载。
希望出这个功能是基于如下场景：
![当前查找结果](https://github.com/user-attachments/assets/1d690edd-e8d4-4f87-b893-6eae90fb44c1)
可以看上图，根据我搜索的关键词查找出来的视频片段，其实是在那句台词之后的。我点开预览，把进度条稍微往前拉一点，恰好看到了我要找的画面。所以我就想把找到的这个片段的开始时间往前调整一点，相应的，结束时间也可以往前拉动一点。然后按照我调整后的开始、结束时间形成一个新片段，下载下来。
具体做法可能可以参考下面这个图，这是一个软件的截图：
![调整裁剪片段](https://github.com/user-attachments/assets/3c1da03d-6e75-485f-a54a-5707a74c3211)
它是可以在预览界面通过拖动开始时间和结束时间的那2条线来灵活的调整真正想要下载下来的片段。
基于以上，希望作者能够加入这个功能。

**Comment by chn-lee-yumi** [comment]
你的想法非常好，但是由于精力有限，我无法实现这个功能。

考虑到大部分人下载视频片段都是用于二次剪辑，因此时间不是很准确并没有什么影响——反正都要再剪的了。

关于你提到的需要把进度条往前拉一点的问题，你可以通过增加`VIDEO_EXTENSION_LENGTH`来解决，这样就能保证你想要的片段不会被截掉，但是多余的片段就需要在剪辑软件后期处理了。

**Comment by gramophone-g** [comment]
1、想做这个功能其实主要是因为搜索找到的片段还不是很精准，就比如我举例的那个图片。我是为了说明场景才截图的，实际上找出的那条视频片段的起始时间点还要更靠后，大约在我要找的那句台词画面的往后3分钟多的地方。也就是说找到的视频片段的开始时间有可能距离我想要的画面有2分钟、3分钟、5分钟…这样不等的时间间隔。这样的话，通过增加 VIDEO_EXTENSION_LENGTH 也许也不能完全解决问题。因为不知道这里设置多少比较好。
2、由上面问题也引出另一个问题，就是可以在扫描的时候将视频的字幕也做成索引吗？这样文搜视频的时候，如果输入了字幕里的内容就可以快速准确定位到画面和视频片段。
3、还想到的一个功能是，在前台展示搜索结果的时候可不可以做“分页”？就是文搜视频的时候，如果超过30个，前台页面就会很卡，我试过设置150个，还没刷出来就页面崩溃然后重置了。有分页功能的话，就可以设置比如每次显示6个（找到的第1-第6个结果），然后鼠标往下滚轮一次，才展示后面6个（找到的第7-第12个结果），再往下滚轮一次，再展示后面6个（找到的第13~第18个结果），就这样直到最后一个结果。其实这个功能本质上也是因为搜索出来的头几个结果不是很符合预期，那么使用人就像再往后面找一找。当然，分页最好是做在后台，也就是每次往下滚轮一次，相当于又发起一起请求，这样前台页面不会崩溃，使用的人也可以一直往下找，找到相似度排名靠后的结果。就有点类似于在搜索引擎里找内容，前面的不合适就会一直往后翻。

**Comment by gramophone-g** [comment]
当然，这些功能要看作者的精力，如果觉得合理可以慢慢实现。

**Comment by chn-lee-yumi** [comment]
> 大约在我要找的那句台词画面的往后3分钟多的地方

你应该描述画面内容，而不是直接粘贴台词。

> 在扫描的时候将视频的字幕也做成索引吗

这个暂时没有做的计划。

> 在前台展示搜索结果的时候可不可以做“分页”

这个是很好的想法，我知道有这个问题，但是我也没有精力去做。后续上了路径筛选功能后可以将就一下。

**Comment by gramophone-g** [comment]
好的，谢谢你的答复。
