### ISSUE TITLE
能否增加按路径+文字搜索图片或视频片段的功能

### ISSUE THREAD

**Issue by gramophone-g** [chn-lee-yumi/MaterialSearch#119]
作者好，目前软件已能实现单独的按路径搜索和按文字搜索，能否在此基础上更进一步，增加按路径+文字搜索图片或视频片段的功能。
就是我的素材是分批准备的。比如我现在有10G的历史剧的视频，放在D盘下的01目录里，扫描之后记录到数据库里了。然后我有弄来一批素材，是科普类的视频放在02目录里。又扫描之后记录到数据库了。后面我搜索的时候，想要做历史类的视频剪辑，这个时候我就想指定从01目录里去搜索，比如搜：清朝皇宫，这时就需要既指定目录路径，又要用到文字搜视频。

**Comment by chn-lee-yumi** [comment]
路径+文字搜索准备做了

**Comment by chn-lee-yumi** [comment]
刚刚更新的版本已添加路径筛选和修改时间范围筛选。你可以通过把对应的目录填到搜索路径里面，来达到你想要的效果。
