### ISSUE TITLE
以图搜视频这块是否有优化计划？

### ISSUE THREAD

**Issue by boxsky** [chn-lee-yumi/MaterialSearch#124]
当前测试视频文件大的话 导入比较慢,目前想提高整体流程速度的话有没有什么建议？是要高配显卡？或者使用多核超多线程的cpu支持？才能提高这个过程的耗时。这个需求在影视剪辑二创应该很强烈,大佬有没有一个思路或者推荐几个库？感觉也有市场

**Comment by chn-lee-yumi** [comment]
你打开任务管理器看看，哪个满了就是哪个不行。
