### ISSUE TITLE
模糊搜索的优化思路是啥

### ISSUE THREAD

**Issue by zhjygit** [chn-lee-yumi/MaterialSearch#125]
测试了一下功能，整体还是很不错。
“手上拿帽子”、“全身红色衣服且戴帽子”
对于这种多任务组合的搜索，搜索准确度一般，如果下一步要在这方面进行深入研究的话，代码处理方面，整体要在哪些模块进行优化？
能否给一些建议，能够快速且高效的进入优化阶段。
期待您的回复。

**Comment by zhjygit** [comment]
当前是在windows上整合包体验了效果，下一步要进行优化的话，建议如何部署环境？直接在win10物理机上使用conda安装指定版本python而后优化，还是在vmware中使用ubuntu18虚拟机进行部署呢？
期待您的回复。

**Comment by chn-lee-yumi** [comment]
能不能说人话？我没懂你在问啥。

**Comment by zhjygit** [comment]
我举个例子哈。文字搜内容或文字搜视频，搜索关键词为“穿红色衣服戴帽子的人”，出来的结果可能是红色衣服或者帽子，但我想要的结果是穿红色且戴帽子的人，那么这个时候涉及到多个feature特征值的重组吗？如何解决这种问题呀

**Comment by chn-lee-yumi** [comment]
> 那么这个时候涉及到多个feature特征值的重组吗

不涉及

> 搜索关键词为“穿红色衣服戴帽子的人”，出来的结果可能是红色衣服或者帽子。如何解决这种问题呀

模型问题，你可以尝试换提示词（例如“穿红色衣服并且戴帽子的人”）或者换模型
