### ISSUE TITLE
模型训练和加载

### ISSUE THREAD

**Issue by zhjygit** [chn-lee-yumi/MaterialSearch#126]
如果我用在自己的场景下，需要加强一些场景的识别能力，比如说桥梁、道路、特种车辆等等，这种情况下，模型训练和加载到这个项目的基本方法，能否简单说明一下，谢谢。

**Comment by chn-lee-yumi** [comment]
你可能需要微调模型。

https://www.bing.com/search?FORM=U523DF&PC=U536&q=finetune+clip

**Comment by zhjygit** [comment]
好的，谢谢，我先看看。

**Comment by zhjygit** [comment]
> 你可能需要微调模型。
> 
> https://www.bing.com/search?FORM=U523DF&PC=U536&q=finetune+clip

微调模型，“手上拿杯子的人”，这种多元素的识别，模型训练起来是不是比较复杂，有没有这种多元素特征的模型可以拿来用或者再微调，一般的模型都是那种“人”“车”“猫”“灯”类型的单目标识别。

**Comment by chn-lee-yumi** [comment]
> 有没有这种多元素特征的模型可以拿来用

没有，你需要自己搜集数据进行微调。具体微调过程我无法提供帮助，因为这超出了本项目的范围。

**Comment by chn-lee-yumi** [comment]
我推荐你直接更换不同的模型看看效果，都不符合你的需求再尝试微调。
