### ISSUE TITLE
大佬。我在飞牛NAS的docker环境下下部署后，打开网址点击扫描没有任何反应，配置文件设置为自动扫描 且设定了时间段也没有反应。

### ISSUE THREAD

**Issue by hanning80** [chn-lee-yumi/MaterialSearch#130]
大佬。我在飞牛NAS的docker环境下下部署后，打开网址点击扫描没有任何反应，配置文件设置为自动扫描 且设定了时间段也没有反应。
![1817212a-50db-49db-ab35-d72fff6dd40b](https://github.com/user-attachments/assets/f6aefb42-8d0a-4ccd-9cc8-080da1013205)
![1](https://github.com/user-attachments/assets/9ce37156-6dc9-4770-b7e4-33c5bbde4b5f)
![2](https://github.com/user-attachments/assets/ec9d6f27-de53-4f96-8a74-875c6f6bd275)
![3](https://github.com/user-attachments/assets/3560d7f1-61e0-4f46-9a15-45f1f8db2bce)
![34](https://github.com/user-attachments/assets/2d68a355-e326-4744-bce1-291679a7f450)

**Comment by chn-lee-yumi** [comment]
配置不对。你这里ASSETS_PATH应该为/home。

**Comment by chn-lee-yumi** [comment]
已更新docker-compose文件说明。

**Comment by hanning80** [comment]
environment: # 通过环境变量修改配置
      - ASSETS_PATH=/home,/mnt
      - SKIP_PATH=/tmp
    volumes:
      - /vol1/1000/docker/MaterialSearch/db:/MaterialSearch/instance/
      - /vol1/1000/movie:/home
      - /vol1/1000/docker/MaterialSearch/config:/mnt
      - /vol1/1000/docker/MaterialSearch/config.env:/MaterialSearch/config.env
      这样修改就对了是吗

**Comment by hanning80** [comment]
已经解决了。谢谢。就是按上面配置就搞定了。 我就是不知道mnt文件夹是做什么用的。
另外在图文相似度匹配页面上传了图片之后（提示上传成功）点击 “计算相似度” 后提示<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
![6](https://github.com/user-attachments/assets/ce754142-379a-4532-9c0d-6eb76d201bfb)
