### ISSUE TITLE
无法实时更新扫描的地址。

### ISSUE THREAD

**Issue by huangbiaocat** [chn-lee-yumi/MaterialSearch#131]
“右键“.env”文件进行编辑，配置扫描路径和设备，然后保存。”
上次填写的地址没扫描完的情况下，修改这个文件，再打开run.bat，依然是继续扫描上次修改前的目录地址。请问如何解决

**Comment by chn-lee-yumi** [comment]
已知问题，已经在todo list。临时解决方案：删除 tmp\assets.pickle

**Comment by huangbiaocat** [comment]
>已知问题，已经在待办事项列表中。临时解决方案：删除tmp\assets.pickle后重启>已知问题，已经在待办事项列表中。临时解决方案：删除tmp\assets.pickle后重启解决了，我也是这么解决的。我是问 GPT 处理的😊
