### ISSUE TITLE
可以在nas环境下运行吗

### ISSUE THREAD

**Issue by obai132** [chn-lee-yumi/MaterialSearch#132]
可以在nas服务器里面进行搜图吗

**Comment by obai132** [comment]
nas里面有几十万张图片，这个软件可以识别吗

**Comment by chn-lee-yumi** [comment]
可以，但是如何部署，我不能提供支持。

**Comment by obai132** [comment]
能帮忙安装吗，有偿发自我的 iPhone在 2024年11月24日，13:31，YumiLee ***@***.***> 写道：﻿
可以，但是如何部署，我不能提供支持。

**Comment by obai132** [comment]
或者可以帮忙安装在windows系统上吗，我们用来拍衣服照片在图库进行查找。发自我的 iPhone在 ***@***.*** 写道：﻿能帮忙安装吗，有偿发自我的 iPhone在 2024年11月24日，13:31，YumiLee ***@***.***> 写道：﻿
可以，但是如何部署，我不能提供支持。
