### ISSUE TITLE
docker，扫描时没调用GPU

### ISSUE THREAD

**Issue by sanwacompany** [chn-lee-yumi/MaterialSearch#133]
我的docker-compose文件应该没错吧？但是扫描过程中我发现CPU占满了，但是GPU没被调用。请问大佬是什么原因呢？如何排查呢？
![微信截图_20241127190132](https://github.com/user-attachments/assets/7c3a2467-3ec4-4564-b856-bcad88e0b357)
![微信截图_20241127190303](https://github.com/user-attachments/assets/be57f8c7-4a72-4192-93a6-303a0d58c5ab)

**Comment by sanwacompany** [comment]
对了，看到docker的log里面，有一行“DEVICE: 'cpu'”

**Comment by grenadn** [comment]
> 对了，看到docker的log里面，有一行“DEVICE: 'cpu'”

看这里
https://github.com/chn-lee-yumi/MaterialSearch/blob/main/config.py
默认 CPU，需要改下 env

**Comment by sanwacompany** [comment]
> > 对了，看到docker的log里面，有一行“DEVICE: 'cpu'”
> 
> 看这里 https://github.com/chn-lee-yumi/MaterialSearch/blob/main/config.py 默认 CPU，需要改下 env

感谢

**Comment by chn-lee-yumi** [comment]
感谢提醒，我现在已经在docker-compose添加需要修改environment的说明
