### ISSUE TITLE
希望"搜索路径"功能对”文字搜索视频“也能起作用。

### ISSUE THREAD

**Issue by lizi1314520** [chn-lee-yumi/MaterialSearch#134]
今天是2024年12月02日，我下载了最新的，经过测试发现："搜索路径"功能,我测试了，对"文字搜图"有用，但对”文字搜视频“没有起作用，大佬能不能加上这个功能呢？
    理由是：我拍摄了比较多的旅游视频：
1：比如说在深圳拍了几天，这些视频放在一个文件夹。
2：去海南又拍了几天，这些视频放在一个文件夹。
3：去广州又拍了几天，这是视频放在一个单独的文件夹。
……
     这时候我想剪辑广州的视频，就可以通过"搜索路径"指定广州视频所在文件夹路径，只搜索到广州的视频素材，这样就会对我的视频剪辑有很大的帮助。

     非常感谢大佬的开源项目，听大佬说只用三天就开发出来了，太牛逼了！！

**Comment by chn-lee-yumi** [comment]
我看了下代码，确实路径对视频没有生效。可能是我当初改这个功能的时候把视频的部分漏改了……这个会尽快修复。

https://github.com/chn-lee-yumi/MaterialSearch/blob/main/search.py#L205

**Comment by lizi1314520** [comment]
卧槽，大佬还真回复了!!!感谢大佬啊,NB!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chn-lee-yumi/MaterialSearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chn-lee-yumi/MaterialSearch] 希望"搜索路径"功能对”文字搜索视频“也能起作用。 (Issue #134)





 
我看了下代码，确实路径对视频没有生效。可能是我当初改这个功能的时候把视频的部分漏改了……这个会尽快修复。
 
https://github.com/chn-lee-yumi/MaterialSearch/blob/main/search.py#L205

**Comment by chn-lee-yumi** [comment]
问题已修复

**Comment by lizi1314520** [comment]
&nbsp; 牛逼呀,感谢大佬!&nbsp; 我刚刚还去看了一下,没想到一下就更新了!!&nbsp; 我去测试一下!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月12日(星期四) 下午5:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chn-lee-yumi/MaterialSearch] 希望&quot;搜索路径&quot;功能对”文字搜索视频“也能起作用。 (Issue #134)














 
问题已修复
