### ISSUE TITLE
网页搜索的时间过长的问题

### ISSUE THREAD

**Issue by Linkersem** [chn-lee-yumi/MaterialSearch#135]
@chn-lee-yumi 你好，我在本地部署了这一套代码，在使用的时候，我发现第一次的搜索的时间是最长的， 后面就会好很多，
但是偶发性的会出现很长的搜索时长，表现为网页端一直在转圈显示搜索的界面，服务端一直没有显示“查询使用时间”的log，这个时候我刷新网页，就会出现databae is lock 的错误，我查询了这个问题，主要是因为目前的代码不支持多个查询同时进行，我想知道，为什么会出现搜索时间很长的现象？

**Comment by Linkersem** [comment]
你好，我数据库只有大约一万张图片，没有视频，出现搜索时常较长的情况下短则20秒，长则100s，但是这一次搜索时间较长的过程过了之后，就可以快速检索，搜索速度大概几十到几百毫秒。

**Comment by chn-lee-yumi** [comment]
你说的快速检索，是搜索同样的词？

你的数据库是否存放在远程目录上？

电脑什么配置？

**Comment by chn-lee-yumi** [comment]
太久无人回复，关闭此issue
