### ISSUE TITLE
期望可以增加影片剪辑截取的功能

### ISSUE THREAD

**Issue by cherryoyo** [chn-lee-yumi/MaterialSearch#14]
非常感谢作者的程序。
我主要是想使用文字搜视频。
有时候做影片剪辑，本地有很多素材，但是找的话确实比较耗时。
看到您开发的程序可以解决这个问题，但是是否可以改进一下，以便程序更加节省人力。
比如，搜出的结果只是显示相关画面出现在哪些影片中，并且是在什么时刻出现的，
但是无法直接剪辑并下载相应的片段，搜索到之后，还需要到相应的影片中截取对应片段。
这一点可以参考33搜帧这个软件，可以对找到的结果进行在线剪辑，并且可以设置需要剪辑的时长。
我想，随着后期程序功能的不断完善，一定可以提高视频剪辑人员的工作效率，帮助到更多的人。

**Comment by cherryoyo** [comment]
›可能是我描述的不太清楚，我说的在线剪辑，就是剪辑出搜索结果中的这几秒匹配片段。
也就是33搜帧的这个功能。
<img width="489" alt="截屏2023-06-13 09 35 48" src="https://github.com/chn-lee-yumi/MaterialSearch/assets/77727525/dd381a57-9963-42b0-a074-af39d2ba67aa">

**Comment by chn-lee-yumi** [comment]
这个功能可以做

**Comment by chn-lee-yumi** [comment]
功能已实现，更新代码即可使用。这个功能依赖ffmpeg，如果你没装需要先装一下。
