### ISSUE TITLE
哈希计算是用在什么地方？

### ISSUE THREAD

**Issue by babyta** [chn-lee-yumi/MaterialSearch#15]
你好，这个哈希计算是提供一种比对方式还是怎么用的？

**Comment by chn-lee-yumi** [comment]
给缓存用的，作为key。

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
