### ISSUE TITLE
测试不支持cuda

### ISSUE THREAD

**Issue by mumutongxueY** [chn-lee-yumi/MaterialSearch#17]
您好，我测试cpu和gpu的时候，会直接显示该平台不支持cuda和mps，已跳过，这个属于正常吗

**Comment by chn-lee-yumi** [comment]
正不正常得看你的硬件。N卡支持cuda，MacOS支持mps。

**Comment by mumutongxueY** [comment]
我的是4060ti，就是测的时候直接跳过了，家里还有一个4090的还没试

**Comment by chn-lee-yumi** [comment]
那可能是因为你没有安装支持cuda的torch。如果你是windows系统，请尝试双击install_gpu.bat安装。

**Comment by mumutongxueY** [comment]
好的好的，我试一试

**Comment by mumutongxueY** [comment]
我双击了gpu.bat，然后也打开了benchmark.bat，依然还是不支持然后跳过了，后面我把配置文件改成cuda，运行的时候直接闪退了

**Comment by chn-lee-yumi** [comment]
命令行执行`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`看看什么输出？

**Comment by mumutongxueY** [comment]
这次多下了一个东西，之前打开好像没下载到torch，这次能用了，然后我用gpu试了一下，速度快了不少，不过感觉利用率不是很高。然后我扫描结束之后搜索好像失败了，我之前出现了这个警告：This is a development server. Do not use it in a production deployment. Use a production WSGI server。所以在main那里的最后改过一点代码：

**Comment by mumutongxueY** [comment]
if __name__ == '__main__':
    init()
    app.run(port=PORT, host=HOST)

改成了

if __name__ == '__main__':
    from gevent import pywsgi

    server = pywsgi.WSGIServer(('0.0.0.0',8085),app)
    server.serve_forever()

以前能用，现在好像不行了

**Comment by chn-lee-yumi** [comment]
这个WARNING已经有相关issue：https://github.com/chn-lee-yumi/MaterialSearch/issues/16 忽略即可。

搜索失败请提供报错信息。

**Comment by mumutongxueY** [comment]
<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by chn-lee-yumi** [comment]
代码报错信息呢？

**Comment by mumutongxueY** [comment]
File "C:\Users\21218\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\21218\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\21218\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\21218\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\MaterialSearch-main\main.py", line 397, in wrapper
    return view_func(*args, **kwargs)
  File "E:\MaterialSearch-main\main.py", line 504, in api_match
    sorted_list = search_video(positive_prompt=data['positive'], negative_prompt=data['negative'],
  File "E:\MaterialSearch-main\main.py", line 338, in search_video
    scores = match_batch(positive_feature, negative_feature, image_features, positive_threshold, negative_threshold)
  File "E:\MaterialSearch-main\process_assets.py", line 209, in match_batch
    positive_scores = (new_features @ new_text_positive_feature.T)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 768 is different from 512)


他在窗口里面报的是这些，这样可以吗，代码不是很懂

**Comment by chn-lee-yumi** [comment]
你这个问题有人问过了。请看：https://github.com/chn-lee-yumi/MaterialSearch/issues/3
