### ISSUE TITLE
支持多线程扫描

### ISSUE THREAD

**Issue by cflzxy** [chn-lee-yumi/MaterialSearch#18]
不知道扫描的时候能否添加多线程扫描，或许能提高扫描效率。

**Comment by chn-lee-yumi** [comment]
本人硬件比较垃圾，目前正常扫描已经几乎吃满资源。很难说这样可以提高效率。

但是对于高端设备来说，或许可以，但是我没有办法测试。

**Comment by chn-lee-yumi** [comment]
我暂时不会投入精力去研究这件事情。如果有人有任何建议或相关的测试结果，欢迎留下评论。如果有证据能证明这个能提高效率，我会投入时间去尝试。
