### ISSUE TITLE
影片搜索裁剪功能的几个小问题

### ISSUE THREAD

**Issue by cherryoyo** [chn-lee-yumi/MaterialSearch#19]
感谢作者刚刚增加的影片搜索结果裁剪功能。
使用这个功能时，我发现了几个小问题。
1.有时搜索出来的视频长度太短，导致截取的视频因太短而无法使用。
<img width="1869" alt="截屏2023-06-18 09 16 48" src="https://github.com/chn-lee-yumi/MaterialSearch/assets/77727525/7ac831f2-e22a-417e-bcbc-4b3caf2e3ebc">

2.截取后的视频，有些无法正常播放，有声音无图像。
<img width="341" alt="截屏2023-06-18 09 19 01" src="https://github.com/chn-lee-yumi/MaterialSearch/assets/77727525/dee31e0d-828c-429e-a228-bbc76c60030c">

**Comment by chn-lee-yumi** [comment]
> 有时搜索出来的视频长度太短，导致截取的视频因太短而无法使用。

这个问题后续会通过新增一个参数（控制截取视频时前后延长长度）来解决。

> 截取后的视频，有些无法正常播放，有声音无图像

这个问题是否可以稳定复现？如果可以，请将完整素材（上传到网盘或别的地方）、用的模型、搜索词、搜索阈值，以及操作步骤发一下，我排查一下。

**Comment by chn-lee-yumi** [comment]
截取视频时前后延长时间的参数已增加：https://github.com/chn-lee-yumi/MaterialSearch/commit/92d1d4b5262422b2baf9b6c891fadb77a5e26512
