### ISSUE TITLE
建议路径去掉作者电脑的信息

### ISSUE THREAD

**Issue by ZhianLin** [chn-lee-yumi/MaterialSearch#2]
路径暴露了一些信息了，建议处理下。
扫描路径可以默认成os.getcwd()
skip可以默认为空。

**Comment by chn-lee-yumi** [comment]
哈哈哈，因为自己在用，感觉改了再上传太麻烦，所以就直接上传了自己在跑的代码了。我的个人信息都不知道卖几手了，想查的肯定能查到。

**Comment by chn-lee-yumi** [comment]
已经优化了，感谢建议

**Comment by ZhianLin** [comment]
> 已经优化了，感谢建议

收到，处理的真是迅速啊。
