### ISSUE TITLE
希望能增加一个按文件名搜索的功能

### ISSUE THREAD

**Issue by cflzxy** [chn-lee-yumi/MaterialSearch#20]
有些文件已经通过文件名进行分类好了，要是能实现这个功能就完美了。感谢作者提供了那么优秀的开源项目

**Comment by chn-lee-yumi** [comment]
这个确实可以，后续有空添加。

**Comment by chn-lee-yumi** [comment]
新功能已增加：https://github.com/chn-lee-yumi/MaterialSearch/commit/b648504ad016afd0263c30f0be21efc555ae4c1b

如有任何问题，欢迎反馈。
