### ISSUE TITLE
测试数据集

### ISSUE THREAD

**Issue by YangLiu14** [chn-lee-yumi/MaterialSearch#24]
非常感谢您的项目。想请问一下您是否知道有什么数据集是可以拿来测试这个retrieval的效果的呢？

**Comment by chn-lee-yumi** [comment]
你是如何定义效果的好坏？如果只是想单纯测试功能，自己随便弄几张图片进去试试就行了。

**Comment by chn-lee-yumi** [comment]
CLIP 的 Model Card 或许能为你提供帮助：https://github.com/openai/CLIP/blob/main/model-card.md
