### ISSUE TITLE
这个项目泰裤辣，不知道扫描速度有没有优化空间

### ISSUE THREAD

**Issue by xiaomayidechuanshuo** [chn-lee-yumi/MaterialSearch#25]
感谢作者提供这么好的图片整理方案，这对于有大量图片的美术人员有很大的帮助，能比之前更好的检索本地图片，但是目前这个软件扫描速度是个问题，我导入了2万多张图片进行测试，显卡3060，扫描用了3个多小时，不知道这里面的速度还有没有提升的优化方案，我对着这个项目太感兴趣了，可以的话能留着常用的邮箱吗，想交流下

**Comment by chn-lee-yumi** [comment]
OK，收到了

**Comment by kangkang623** [comment]
我的硬盘百十万张图片，cpu扫描要100多天，哈哈哈，算了，不玩了，想快就只能换电脑了

**Comment by chn-lee-yumi** [comment]
> 我的硬盘百十万张图片，cpu扫描要100多天，哈哈哈，算了，不玩了，想快就只能换电脑了

你这个问题，确实，充钱（换电脑）可以解决。

**Comment by muxuan1978** [comment]
文件多了，搜索也会很慢，服务器不行根本搜不动

**Comment by chn-lee-yumi** [comment]
> 文件多了，搜索也会很慢，服务器不行根本搜不动

多少文件，什么硬件配置？
