### ISSUE TITLE
特征提取有什么推荐的其他方法吗？

### ISSUE THREAD

**Issue by babyta** [chn-lee-yumi/MaterialSearch#26]
现在用是clip，请问一下，有其他的文本，图像提特征方法吗，可能觉得512维度特征不够用。谢谢。

**Comment by babyta** [comment]
谢谢！

**Comment by babyta** [comment]
你好我想问下clip这个不需要对图像进行统一缩放吗？

**Comment by chn-lee-yumi** [comment]
> 你好我想问下clip这个不需要对图像进行统一缩放吗？

不需要自己操作

**Comment by chn-lee-yumi** [comment]
`CLIPImageProcessor`对图像进行处理的过程中会进行缩放：https://huggingface.co/docs/transformers/v4.33.3/en/model_doc/clip#transformers.CLIPImageProcessor

图像的短边会被缩放到224px，长边等比例缩放，然后对中心区域进行裁剪，得到224x224大小的图片，再丢给模型处理。
