### ISSUE TITLE
Mac os 10.14 安装opencv-python-headless>=4.5.5.64 失败解决方方法

### ISSUE THREAD

**Issue by stoneFive** [chn-lee-yumi/MaterialSearch#27]
Mac os 10.14 安装 opencv-python-headless>=4.5.5.64 失败可以使用 
`pip install opencv-python-headless==4.7.0.68` 安装 目前使用python3.8.3 环境下pip 可以安装成功。

**Comment by chn-lee-yumi** [comment]
感谢反馈，已修改requirements.txt。https://github.com/chn-lee-yumi/MaterialSearch/commit/df56eb989453bbbfd690597de41570ea548dc73c
