### ISSUE TITLE
关于集成测试test_api_status

### ISSUE THREAD

**Issue by chn-lee-yumi** [chn-lee-yumi/MaterialSearch#38]
From @cccxp : 我感觉没理由假设刚开始就在扫描中（提前扫描过一遍有可能导致这里不过），把等待扫描完成移到scan里就够了？这个问题在Github workflow里面倒是不会遇到。

**Comment by chn-lee-yumi** [comment]
我看了下代码，因为pytest是按照代码顺序一个个执行的，前面调用了test_api_scan，会确保正在扫描，然后再调用test_api_status，也是会正在扫描，所以这里用`assert data["status"] is True`。

> 提前扫描过一遍有可能导致这里不过

应该不会出现这种问题，这几个请求间隔非常短，就算已经扫描过，重新扫描的时间应该也会比这个长。

这个集成测试代码路径写死了，针对github的runner……所以好像不是很方便进行本地测试……先将就用着吧……后面看看咋优化，集成测试里面还有一堆TODO。

@cccxp

**Comment by ericyq** [comment]
文字搜图
返回：JSON格式，可以使用以下命令：
curl -X POST http://127.0.0.1:8085/api/match -H "Content-Type: application/json" -d '{
    "positive": "a dog",
    "negative": "",
    "top_n": "6",
    "search_type": 0,
    "positive_threshold": 10,
    "negative_threshold": 10,
    "image_threshold": 85,
    "img_id": -1,
    "path": "/data/images",  ***说明：服务器上存放图像的原目录
    "start_time": null,
    "end_time": null
}'

返回：
[{"path":"/data/images/0801/582_dog1.jpg","score":0.41561782360076904,"url":"api/get_image/2"},{"path":"/data/images/0604/415_dog2.jpg","score":0.4139259457588196,"url":"api/get_image/67"}]
