### ISSUE TITLE
不支持pillow 10.1.0

### ISSUE THREAD

**Issue by cuiyan1989** [chn-lee-yumi/MaterialSearch#39]
安装GPU支持的时候提示：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.31.6 requires pillow<10.1.0,>=8.3.2, but you have pillow 10.1.0 which is incompatible.

**Comment by chn-lee-yumi** [comment]
?

**Comment by cuiyan1989** [comment]
抱歉，没有留下解决防范就关闭了issues。出现错误的原因是：

这个错误是由于包依赖关系冲突导致的。具体而言，imageio 要求安装的是 pillow 版本小于 10.1.0 且大于等于 8.3.2，但你的环境中已经安装了 pillow 的 10.1.0 版本，这两个版本不兼容。

解决方案：
降级 pillow：
pip install pillow==8.3.2

重新再次安装GPU依赖就可以了。
