### ISSUE TITLE
“预估剩余时间”显示的问题，现在貌似显示的是全部扫描所需的时间

### ISSUE THREAD

**Issue by tdstorm** [chn-lee-yumi/MaterialSearch#40]
作者你好，非常感谢你开发的这个项目，帮了我很大的忙。

遇到的问题是：
1.扫描时显示的“预估剩余时间”没有随着扫描进度减少 ，反而一直保持着刚开始扫描时的大概时间，这个时间也会随时发生变化，不过是在几个小时的范围内波动，貌似一直显示的是“全部扫描所需的大概时间”的样子。例如下方这张截图
![QQ截图20231120163026](https://github.com/chn-lee-yumi/MaterialSearch/assets/47531411/676c0bc4-79e0-496e-862a-5e1c4eb39e46)
这个是现在的扫描进度，显示的时间却跟2天前我点击开始扫描后显示的时间差不多，但按照目前的扫描速度，大约会在1个半小时后扫描结束。，这个问题在我11月18日更新镜像前也是存在的。

2.还有个小疑问，我在更新镜像前扫完成过一次，更新镜像后好像没有扫描记录了，程序是从头开始扫描的，我看了下目录，.db文件还是在的，大小和日期与我之前扫描完成后相同。是不是每次更新镜像后的扫描都会从头开始扫描呢？

我的设备:
我使用的设备是NAS，系统为UNRAID，用的是docker的版本，镜像在11月18日晚上有提示更新，就更新了。很抱歉我不知道如何在docker中显示像在windows系统上运行main.py文件后显示的内容，镜像的配置没有调整过，跟docker-compose.yml文件里面一样，没有增加或减少参数，只是改了图片目录。硬件配置是CPU 11900K，内存64G，没有限制CPU使用量和内存使用量。

**Comment by tdstorm** [comment]
好的谢谢，我试试

**Comment by chn-lee-yumi** [comment]
> 好的谢谢，我试试

镜像还没推上去，等这个action跑完就可以了：https://github.com/chn-lee-yumi/MaterialSearch/actions/runs/6930093037/job/18849184290

**Comment by tdstorm** [comment]
刚刚更新镜像测试了一下，现在可以读取以前的数据库了，非常感谢
