### ISSUE TITLE
请教一下，huggingface是必须的吗？

### ISSUE THREAD

**Issue by Mr-z-j** [chn-lee-yumi/MaterialSearch#41]
假如将服务内网使用，huggingface.co 无法访问时，服务无法启动。

请问huggingface的连接是必须的吗？

**Comment by chn-lee-yumi** [comment]
如果模型已经下载好了，可以通过设置环境变量TRANSFORMERS_OFFLINE=1来跳过版本检查

**Comment by zzzzzz7** [comment]
您好,邮件已经收到;我会尽快和您联系。虽然这是一封自动回复邮件，但是我会每天查看邮箱！保证您的邮件在第一时间看到！

**Comment by zzzzzz7** [comment]
> TRANSFORMERS_OFFLINE=1

感谢。

另外再请教一个问题：
当前使用的AI模型，是否可以忽略图片的背景底色进行特征码匹配？

**Comment by chn-lee-yumi** [comment]
> 另外再请教一个问题： 当前使用的AI模型，是否可以忽略图片的背景底色进行特征码匹配？

不是很懂你的意思。模型是吃整个图片的。

**Comment by zzzzzz7** [comment]
> > 另外再请教一个问题： 当前使用的AI模型，是否可以忽略图片的背景底色进行特征码匹配？
> 
> 不是很懂你的意思。模型是吃整个图片的。

![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/33717746/b3bd6668-e821-44a8-a00d-5511e22f9eb1)


举个粒子，黄色框内的是样例图，我想要的结果是搜到绿色框内的结果，但搜索出的结果包含了一个红色框的，而且匹配度有80多呢

**Comment by zzzzzz7** [comment]
> > 另外再请教一个问题： 当前使用的AI模型，是否可以忽略图片的背景底色进行特征码匹配？
> 
> 不是很懂你的意思。模型是吃整个图片的。

![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/33717746/bedbf9d5-1f90-499d-b640-978a43276c7a)

 这张图更明显一点

**Comment by chn-lee-yumi** [comment]
这个没有办法做到。

**Comment by chn-lee-yumi** [comment]
You haven't reply to this issue for 2 weeks. I think your issue have been solved, so I will close this issue. If you have any other questions, please feel free to open a new one.
