### ISSUE TITLE
process_assets.py， line 231，ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 768 is different from 512)

### ISSUE THREAD

**Issue by Mr-z-j** [chn-lee-yumi/MaterialSearch#43]
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/33717746/772ae30f-d781-4db8-a972-c31e5486497d)

我将环境变量中的模型修改之后报错了

![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/33717746/1af2b1fe-490f-43ea-bf33-aa00c23728b1)

**Comment by Mr-z-j** [comment]
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/33717746/fb10c74a-bc43-405a-9a09-961ddfc333b1)


删除数据库 重新扫描后，搜索可以用了。

但是扫描的过程中，8G显卡提示OOM

**Comment by chn-lee-yumi** [comment]
尝试减少`SCAN_PROCESS_BATCH_SIZE`看看

**Comment by chn-lee-yumi** [comment]
> 另外，我在学习源码的过程中发现，这个余弦相似度的计算是直接将数据库里所有的数据全都返回了，然后遍历计算出分数，假如图片数据过多的话，比如说10万张图片，这个速度是不是会越来越慢？？

很明显是的

**Comment by chn-lee-yumi** [comment]
You haven't reply to this issue for 2 weeks. I think your issue have been solved, so I will close this issue. If you have any other questions, please feel free to open a new one.
