### ISSUE TITLE
建议添加网络代理的配置选项

### ISSUE THREAD

**Issue by lyyhui1314** [chn-lee-yumi/MaterialSearch#46]
模型中需要访问huggingface.co，网络状况十分糟糕，建议添加全局代理的选项
Windows下可使用如下代码:

import os

os.environ['http_proxy'] = '代理地址'
os.environ['https_proxy'] = '代理地址'

**Comment by chn-lee-yumi** [comment]
这个其实在执行main.py前自行设定就可以了吧？

**Comment by chn-lee-yumi** [comment]
Readme已更新：https://github.com/chn-lee-yumi/MaterialSearch/commit/1fc8df1a6609d4b7f81299629b49a9e1214ac781
