### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by gusaijie** [chn-lee-yumi/MaterialSearch#47]
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-base-patch32/resolve/main/config.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018517C26D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))"), '(Request ID: b54209ec-4b9d-4879-a263-22331a8de776)')

**Comment by gusaijie** [comment]
![Uploading image.png…]()
已经创建了.env文件

**Comment by gusaijie** [comment]
![2](https://github.com/chn-lee-yumi/MaterialSearch/assets/85094785/9811bad1-598b-49be-86d6-435160a42d14)

**Comment by chn-lee-yumi** [comment]
> ProxyError('Unable to connect to proxy'

检查你的代理，是不是没启动

**Comment by gusaijie** [comment]
怎么配置代理，求助一下

**Comment by chn-lee-yumi** [comment]
> 怎么配置代理，求助一下

你用什么代理，去翻文档，或者百度一下
