### ISSUE TITLE
关于搜索速度的想法

### ISSUE THREAD

**Issue by lyyhui1314** [chn-lee-yumi/MaterialSearch#49]
感觉搜索速度还是有点慢，因为我本地有几十T的数据要处理，在想要不要用milvus数据库重构一下

**Comment by chn-lee-yumi** [comment]
好想法。用向量数据库进行优化一直是一个没有开始做的TODO。你可以试一下。

**Comment by chn-lee-yumi** [comment]
由于长期无人回复，此issue关闭。
