### ISSUE TITLE
搜索视频时无法播放，并且get请求出现404

### ISSUE THREAD

**Issue by ZaiPingWang** [chn-lee-yumi/MaterialSearch#5]
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/128682290/a93b8115-7dec-420f-8b89-e0c16dfcc1e8)
大佬您好，我是win10系统，当搜索视频时，能够搜索出来，但是get视频请求出现了404，我扫描了二三十个视频后出现了404，但是我一开始扫描只有一个视频，get请求并没有404。于是我删除了instance目录下的assets.db，再次扫描一个视频，但是搜索出现的get_video请求还是404，视频无法播放，但是可以搜索出来，mp4格式的视频。想问问这种该如何去处理

**Comment by ZaiPingWang** [comment]
应该是文件名存在中文的问题，或者是文件名存在异常符号问题，把文件名改成数字重新扫描就可以了

**Comment by chn-lee-yumi** [comment]
这个确实是我代码bug。目前已修复：https://github.com/chn-lee-yumi/MaterialSearch/commit/5c47163d3c5588e5e0f9509523b01ff661f5b5f1
