### ISSUE TITLE
Server Error</h1> <p>The server encountered an internal error and was unable to completeyour request.

### ISSUE THREAD

**Issue by gusaijie** [chn-lee-yumi/MaterialSearch#50]
![747e23b994c4584c633c86b91e051ff](https://github.com/chn-lee-yumi/MaterialSearch/assets/85094785/09b1659a-fdc7-4715-b986-a64eae5d70d6)

Server Error</h1> <p>The server encountered an internal error and was unable to completeyour request. Either the server is overloaded or there is an error in the application.</p>

这个问题有碰到过吗

**Comment by chn-lee-yumi** [comment]
看看后端报错？

**Comment by gusaijie** [comment]
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/85094785/10079524-1133-4231-b152-24d3ae9435b1)

**Comment by chn-lee-yumi** [comment]
你这个看上去不是最新的代码。拉最新的代码试试？
