### ISSUE TITLE
“运行”文件中填写的扫描路径有中文时，会识别成乱码，扫描失败

### ISSUE THREAD

**Issue by diablo910407** [chn-lee-yumi/MaterialSearch#51]
![1703494947670](https://github.com/chn-lee-yumi/MaterialSearch/assets/136463317/8bc8fd82-ca59-4752-b621-b3b3beb72dc1)
我装的是windows整合包子目录有中文是没问题的，就是在运行文件手动填写的路径有中文就无法扫描

**Comment by diablo910407** [comment]
另外问下大神，上面的路径中能支持①这种符号吗？

**Comment by chn-lee-yumi** [comment]
这个看起来是bat文件的编码问题。可以尝试找下解决办法：https://www.bing.com/search?FORM=U523DF&PC=U536&q=cmd%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81

**Comment by chn-lee-yumi** [comment]
> 另外问下大神，上面的路径中能支持①这种符号吗？

理论上是都支持的

**Comment by chn-lee-yumi** [comment]
我没中文Windows电脑，没办法测。靠你了。测完麻烦在这贴下解决办法。

**Comment by diablo910407** [comment]
https://cloud.tencent.com/developer/article/1835811
确实是编码问题，按照链接里的方法更改设置，然后重启电脑再运行就不会乱码了。现在路径名识别正确，且能顺利扫描到文件了

**Comment by diablo910407** [comment]
使用一段时间后回来反馈，按照上面的方法更改设置后，本软件使用没有问题，但电脑里原来的软件有的运行之后乱码了。要想使用其他软件还得把电脑设置还原回去，很不方便。希望作者大佬有空的话研究一下编码适配，感谢

**Comment by chn-lee-yumi** [comment]
> 使用一段时间后回来反馈，按照上面的方法更改设置后，本软件使用没有问题，但电脑里原来的软件有的运行之后乱码了。要想使用其他软件还得把电脑设置还原回去，很不方便。希望作者大佬有空的话研究一下编码适配，感谢

试试修改bat文件，在最前面添加一行：

```
chcp 65001
```

**Comment by mayichen1987** [comment]
用notepad打开，存为ANSI编码即可

**Comment by diablo910407** [comment]
> > 使用一段时间后回来反馈，按照上面的方法更改设置后，本软件使用没有问题，但电脑里原来的软件有的运行之后乱码了。要想使用其他软件还得把电脑设置还原回去，很不方便。希望作者大佬有空的话研究一下编码适配，感谢
> 
> 试试修改bat文件，在最前面添加一行：
> 
> ```
> chcp 65001
> ```

 用这个方法解决啦
