### ISSUE TITLE
希望可以增加deepdanbooru识别算法

### ISSUE THREAD

**Issue by MinagiCN** [chn-lee-yumi/MaterialSearch#52]
希望可以增加deepdanbooru识别算法,deepdanbooru有较为完善的tag体系,可以实现比起自然语言更高效和精确的图片描述和关键词搜索.

**Comment by chn-lee-yumi** [comment]
我去看了下它的仓库 https://github.com/KichangKim/DeepDanbooru

> DeepDanbooru is anime-style girl image tag estimation system.

看样子并不通用？

**Comment by chn-lee-yumi** [comment]
由于长期无人回复，此issue关闭。
