### ISSUE TITLE
能否增加数据库清空，或者数据库选择的功能，谢谢

### ISSUE THREAD

**Issue by mayichen1987** [chn-lee-yumi/MaterialSearch#53]
instance/assets.db
你好，有没有数据库清空，或者数据库选择，我发现图片删除或者换文件夹后，重新扫描，数据库没有清空，还是原来的大小

**Comment by chn-lee-yumi** [comment]
这是SQLite3本身的设计决定的。删除数据后文件大小不会变小，但是里面的空间可以用来存新的数据。

如果你真的很在意这一点空间，你可以参考这个方法对数据库进行清理：https://blog.csdn.net/wtt234/article/details/124475011

这个功能我不打算在项目内实现。

**Comment by mayichen1987** [comment]
> 这是SQLite3本身的设计决定的。删除数据后文件大小不会变小，但是里面的空间可以用来存新的数据。
> 
> 如果你真的很在意这一点空间，你可以参考这个方法对数据库进行清理：https://blog.csdn.net/wtt234/article/details/124475011
> 
> 这个功能我不打算在项目内实现。

谢谢

**Comment by jianhudiyi** [comment]
我在实际使用中发现，扫描过的视频，你即使删除视频的本地文件，但在项目搜索中仍然会出现不过预览图是黑的，这部分数据并不会实时消失，即使我重新再扫描一遍。只能在.env文件中配置新的目录并扫描，才能解决

**Comment by jianhudiyi** [comment]
我在实际使用中发现，扫描过的视频，你即使删除视频的本地文件，但在项目搜索中仍然会出现不过预览图是黑的。这部分数据并不会实时消失，即使我重新再扫描一遍。只能在.env文件中配置新的目录并扫描，才能解决

**Comment by chn-lee-yumi** [comment]
> 我在实际使用中发现，扫描过的视频，你即使删除视频的本地文件，但在项目搜索中仍然会出现不过预览图是黑的。这部分数据并不会实时消失，即使我重新再扫描一遍。只能在.env文件中配置新的目录并扫描，才能解决

已知问题，已在TODO List

**Comment by chn-lee-yumi** [comment]
> 我在实际使用中发现，扫描过的视频，你即使删除视频的本地文件，但在项目搜索中仍然会出现不过预览图是黑的。这部分数据并不会实时消失，即使我重新再扫描一遍。只能在.env文件中配置新的目录并扫描，才能解决

我无法复现这个的问题。我首先扫描一遍，然后把视频删除，再重新扫描，就搜不出来了。
