### ISSUE TITLE
MaterialSearchWindows如何更新？

### ISSUE THREAD

**Issue by mayichen1987** [chn-lee-yumi/MaterialSearch#54]
我看到源码还在不断更新，十分欣喜，辛苦大佬。
但是MaterialSearchWindows集成板，如何更新，我下载code覆盖后运行报错。

**Comment by chn-lee-yumi** [comment]
现在版本更新没有做兼容，如果用以往的整合包直接覆盖代码是会报错的。

用这个版本的应该可以直接覆盖：https://github.com/chn-lee-yumi/MaterialSearch/tree/0465596180e46c9d888e18c0c082a6600beb1ad5

比这个版本更新的版本，覆盖代码后需要删库重扫。另外由于模型的更换，需要把启动脚本里面的`TRANSFORMERS_OFFLINE=1`删掉，让它重新下载新的模型。

如果经过以上操作还有报错，请贴报错截图。

**Comment by mayichen1987** [comment]
> 现在版本更新没有做兼容，如果用以往的整合包直接覆盖代码是会报错的。
> 
> 用这个版本的应该可以直接覆盖：https://github.com/chn-lee-yumi/MaterialSearch/tree/0465596180e46c9d888e18c0c082a6600beb1ad5
> 
> 比这个版本更新的版本，由于模型的更换（并且不兼容旧的模型了），覆盖代码后需要删库重扫，且需要把启动脚本里面的`TRANSFORMERS_OFFLINE=1`删掉，让它重新下载新的模型。
> 
> 如果经过以上操作还有报错，请贴报错截图。

收到，感谢，马上去试(*^▽^*)

**Comment by mayichen1987** [comment]
> 现在版本更新没有做兼容，如果用以往的整合包直接覆盖代码是会报错的。
> 
> 用这个版本的应该可以直接覆盖：https://github.com/chn-lee-yumi/MaterialSearch/tree/0465596180e46c9d888e18c0c082a6600beb1ad5
> 
> 比这个版本更新的版本，由于模型的更换（并且不兼容旧的模型了），覆盖代码后需要删库重扫，且需要把启动脚本里面的`TRANSFORMERS_OFFLINE=1`删掉，让它重新下载新的模型。
> 
> 如果经过以上操作还有报错，请贴报错截图。

E:\MaterialSearchWindows\lib\site-packages\transformers\utils\hub.py:123: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Traceback (most recent call last):
  File "E:\MaterialSearchWindows\MaterialSearch\main.py", line 25, in <module>
    from utils import crop_video, get_hash, softmax, resize_image_with_aspect_ratio
  File "E:\MaterialSearchWindows\MaterialSearch\utils.py", line 8, in <module>
    from pillow_heif import register_heif_opener
ModuleNotFoundError: No module named 'pillow_heif'

我要用原来的main.py和utils.py替换掉新的吗？

**Comment by chn-lee-yumi** [comment]
对了，多加了一个依赖，你还需要用pip安装`pillow-heif`这个包。

**Comment by chn-lee-yumi** [comment]
已经超过一周没收到回复，所以关闭此issue。如果还有后续问题，可以reopen这个issue。
