### ISSUE TITLE
Mac中使用以图搜图功能视频内容不显示问题

### ISSUE THREAD

**Issue by tty818** [chn-lee-yumi/MaterialSearch#55]
<img width="959" alt="截屏2024-02-18 09 58 53" src="https://github.com/chn-lee-yumi/MaterialSearch/assets/54985567/ff733ffd-8a96-418a-aac5-3d26699658df">
您好想问一下，Mac中使用以图搜图功能视频内容不显示问题，这个是什么问题？望回复

**Comment by chn-lee-yumi** [comment]
看样子是你的浏览器不支持avi播放。这个问题在README.md里面已经有说明了，请见“已知问题”。
