### ISSUE TITLE
搜索图片能否支持粘贴上去?

### ISSUE THREAD

**Issue by veainilo** [chn-lee-yumi/MaterialSearch#56]
如题, 因为经常需要截图去搜索图片, 现在需要先保存在拖拽或者打开.

**Comment by chn-lee-yumi** [comment]
我用的`element-plus`框架并没有提供粘贴上传的功能，所以暂时无法实现。

**Comment by veainilo** [comment]
> 我用的`element-plus`框架并没有提供粘贴上传的功能，所以暂时无法实现。

了解了, 感谢.
