### ISSUE TITLE
博主可以借鉴一下33搜帧的思路

### ISSUE THREAD

**Issue by curui** [chn-lee-yumi/MaterialSearch#58]
https://fse.agilestudio.cn/  
还有一个项目 

https://github.com/yoeven/ai-video-search-engine

**Comment by ld202167** [comment]
我一直想做这个事  数据不太好弄  有没有什么好的办法

**Comment by chn-lee-yumi** [comment]
谢谢，我有空的时候去看看

**Comment by chn-lee-yumi** [comment]
我看了下33搜帧，但是没懂你想说的33搜帧的思路是啥？

**Comment by chn-lee-yumi** [comment]
我看了https://github.com/yoeven/ai-video-search-engine，但是没懂你想要啥？

**Comment by chn-lee-yumi** [comment]
一周无回复，关闭issue。如果后续有问题，欢迎继续留言讨论。
