### ISSUE TITLE
部署在NAS的docker上，每次扫描到一半会显示扫描完成，然后又要重新扫描

### ISSUE THREAD

**Issue by itrycn** [chn-lee-yumi/MaterialSearch#6]
有一万多文件需要扫描，但是每次都只扫描一部分就显示扫描完成了，所以都要过一会再点击扫描进行继续扫描。要经历很多次才能把全部文件扫描完。

**Comment by chn-lee-yumi** [comment]
是否有相关日志？我的NAS有五万个文件，扫了也没问题啊……

**Comment by itrycn** [comment]
> 是否有相关日志？我的NAS有五万个文件，扫了也没问题啊……

好像找到问题了，我刚开始给该容器设置的是1G内存限制，后来放宽到2G内存，就能扫很久了。可能是内存不足导致的。另外能不能加入定时索引功能？如果每次打开再索引，在需要搜索的时候等索引，会比较浪费时间。如果能支持在后台默默索引会更好。还有就是docker版搜出的视频很多播放不了。。。

**Comment by chn-lee-yumi** [comment]
如果数据量大，可能需要扫描几天。你想要的定时索引功能是指，用户可以设置半夜某个时间段来进行自动扫描，等到白天自动暂停，晚上自动继续？

视频很多播放不了，可以尝试重新pull一下镜像，我昨天修了一个bug（https://github.com/chn-lee-yumi/MaterialSearch/issues/5）

如果最新镜像还是不能播放，检查一下编码格式浏览器是否支持（见 https://github.com/chn-lee-yumi/MaterialSearch/blob/main/README.md#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98 ）。另外看看代码是否有报错。

**Comment by itrycn** [comment]
> 如果数据量大，可能需要扫描几天。你想要的定时索引功能是指，用户可以设置半夜某个时间段来进行自动扫描，等到白天自动暂停，晚上自动继续？
> 
> 视频很多播放不了，可以尝试重新pull一下镜像，我昨天修了一个bug（#5 ）
> 
> 如果最新镜像还是不能播放，检查一下编码格式浏览器是否支持（见 https://github.com/chn-lee-yumi/MaterialSearch/blob/main/README.md#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98 ）。另外看看代码是否有报错。

我看都要自己手动扫描，设置里是可以开启启动时扫描。但是如果我新增了大量照片，过了几天后，我想找一张照片，打开网页，还要先扫描一下，才能搜索到全部照片。如果能支持每隔几小时就在后台自动扫描一下，或者每天凌晨自动扫描下，这样我想搜索的时候，就直接可以搜索，不用再扫描了。。。
另外新版镜像我试下看看。

**Comment by chn-lee-yumi** [comment]
自动扫描功能后续加~

**Comment by chn-lee-yumi** [comment]
自动扫描功能已添加，config.py文件有变更。详见config.py里面的注释。

**Comment by itrycn** [comment]
> 自动扫描功能已添加，config.py文件有变更。详见config.py里面的注释。

太感谢了。。。这样就方便多了，我docker马上更新下看看。

**Comment by stoneFive** [comment]
Mac os 10.14 使用python 版本目前安装 opencv-python-headless>=4.5.5.64 装不成功请问用那个版本合适

**Comment by chn-lee-yumi** [comment]
> Mac os 10.14 使用python 版本目前安装 opencv-python-headless>=4.5.5.64 装不成功请问用那个版本合适

你可以试试不指定版本直接用最新。如果不行请贴报错。

**Comment by hnjyzzy** [comment]
Unused or unrecognized kwargs: padding.扫描不完就出错
