### ISSUE TITLE
为什么tga格式的图片不显示？

### ISSUE THREAD

**Issue by liuyixiao666** [chn-lee-yumi/MaterialSearch#61]
![捕获](https://github.com/chn-lee-yumi/MaterialSearch/assets/66301892/f8e1a880-ec1d-4096-80c6-402c1345b4e2)

**Comment by chn-lee-yumi** [comment]
请先阅读`README.md`，里面提到了：

> 部分图片和视频无法在网页上显示，原因是浏览器不支持这一类型的文件（例如tiff文件，svq3编码的视频等）。

**Comment by liuyixiao666** [comment]
没有办法解决吗？

**Comment by chn-lee-yumi** [comment]
> 没有办法解决吗？

应该有：https://github.com/vthibault/tga.js

但我没有这个计划。
