### ISSUE TITLE
自己手动下载的模型文件如何才能识别

### ISSUE THREAD

**Issue by kebinzhi** [chn-lee-yumi/MaterialSearch#62]
cmd下载老是失败，自己到huggingface下载了模型，OFA-Sys/chinese-clip-vit-base-patch16所有文件都下载了。

所有文件放入：MaterialSearchWindows\huggingface\models--OFA-Sys--chinese-clip-vit-base-patch16
无法识别

**Comment by chn-lee-yumi** [comment]
> 如果在被回复前已自行解决问题，推荐留下解决步骤，赠人玫瑰，手有余香。

所以你是怎么解决的？
