### ISSUE TITLE
请问“文字搜视频”功能，是根据视频的配音来搜的吗？

### ISSUE THREAD

**Issue by myqv** [chn-lee-yumi/MaterialSearch#66]
请问“文字搜视频”功能，是根据视频的配音来搜的吗？我这边搜了一下，匹配度很低。

**Comment by chn-lee-yumi** [comment]
原理是每隔一段时间从视频里抽一帧图片，一个视频会抽出许多张图，匹配的时候通过匹配这些图片，定位到符合要求的图片所在的视频时间。
