### ISSUE TITLE
整合包报错：huggingface版本低

### ISSUE THREAD

**Issue by LittleTerry** [chn-lee-yumi/MaterialSearch#68]
感谢作者提供整合包！但是按照说明运行后，报错：

![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/19617725/6d3abb68-03fb-40c8-a79f-46336acc179f)

**Comment by LittleTerry** [comment]
按提示升级版本后可正常运行

**Comment by chn-lee-yumi** [comment]
不应该啊，我看打包记录里面版本是没问题的：

> Collecting huggingface-hub<1.0,>=0.23.0 (from transformers>=4.28.1->-r MaterialSearchWindows/requirements.txt (line 7))
  Downloading huggingface_hub-0.23.1-py3-none-any.whl.metadata (12 kB)

你的电脑是不是已经装了python环境？我怀疑是import的优先级导致的。
