### ISSUE TITLE
整合包找不到视频

### ISSUE THREAD

**Issue by LittleTerry** [chn-lee-yumi/MaterialSearch#69]
按照整合包的使用提示，正常跑起来了，能识别到自定义的路径：
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/19617725/e98b4e00-4f73-481e-bef2-78eade036cb6)

![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/19617725/b17b4688-8469-4725-a950-dbb2a7fcb39d)

但是找不到视频（下图中的视频都是可以正常用potplayer播放器播放）：
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/19617725/0d4e79a0-ef2b-4726-9216-8a870b4e62f7)

**Comment by chn-lee-yumi** [comment]
点扫描，终端有什么报错提示吗？

**Comment by chn-lee-yumi** [comment]
参考你之前的issue（#68），有可能是一些包版本不对导致的玄学问题？你可以尝试更新所有包的版本试试：https://github.com/chn-lee-yumi/MaterialSearch/blob/main/requirements.txt

**Comment by chn-lee-yumi** [comment]
一周无人回复，关闭此issue
