### ISSUE TITLE
以一种访问权限不允许的方式做了一个访问套接字的尝试

### ISSUE THREAD

**Issue by ZhianLin** [chn-lee-yumi/MaterialSearch#7]
系统 window11 家庭版

用0.0.0.0IP启动突然提示“以一种访问权限不允许的方式做了一个访问套接字的尝试”，启动IP换成127.0.0.1就可以，用`netstat -ano|findstr 8085`没有查到端口占用。

**Comment by chn-lee-yumi** [comment]
我没有win11，这个我没有办法测试。你可以尝试重启电脑，然后看看还会不会报错？
