### ISSUE TITLE
faster-whisper 1.0.1 requires tokenizers<0.16,>=0.13, but you have tokenizers 0.19.1 which is incompatible.

### ISSUE THREAD

**Issue by openainext** [chn-lee-yumi/MaterialSearch#70]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
faster-whisper 1.0.1 requires tokenizers<0.16,>=0.13, but you have tokenizers 0.19.1 which is incompatible.

**Comment by chn-lee-yumi** [comment]
这似乎和本项目无关？

**Comment by lzg134679** [comment]
这是环境问题，tokenizers的版本装错了，faster-whisper 1.0.1 要求tokenizers的版本要小于0.16，大于等于0.13，你现在装的是0.19.1
