### ISSUE TITLE
能否推出工作区或类似的功能？

### ISSUE THREAD

**Issue by Jackxwb** [chn-lee-yumi/MaterialSearch#74]
比如：新建一个工作区，使用自己独立数据库，自己独立的扫描目录（动态修改）、过滤参数。
我想用来管理我的二次元图片，也想用来管理我拍的照片，但我不希望我搜索不同的照片时，搜出大量不是这个主题的图片。
如果只作为Window下的小工具，按需创建bat启动脚本也能实现，但我希望它常驻到nas上，然后需要的时候就能立刻搜索了

_Originally posted by @Jackxwb in https://github.com/chn-lee-yumi/MaterialSearch/issues/12#issuecomment-2141952820_

**Comment by capp-adocia** [comment]
是类似于把自己的图片上传到云端数据库里，方便以后查找？

**Comment by capp-adocia** [comment]
是类似于把自己的图片上传到云端数据库里，方便以后查找？

**Comment by chn-lee-yumi** [comment]
> 是类似于把自己的图片上传到云端数据库里，方便以后查找？

不是，是不同的扫描目录

**Comment by chn-lee-yumi** [comment]
刚刚更新的版本已添加路径筛选和修改时间范围筛选。你可以通过把对应的目录填到搜索路径里面，来达到你想要的效果。
