### ISSUE TITLE
cuda加速安装脚本问题，以及其余bat脚本问题及解决方法

### ISSUE THREAD

**Issue by lzg134679** [chn-lee-yumi/MaterialSearch#75]
问题1：文件内的几个需要调用python的bat脚本，路径使用了  ./python.exe ……，在win11环境运行会报错，可能win11需要强制使用反斜杠表示路径，应该改为  .\python.exe ……，修改后运行正常

问题2：cuda加速安装脚本
我下载的20240604版本整合包，发现整合包内的环境自带了cpu版本的torch，并且安装cuda版本的bat脚本中并没有先卸载原有的torch
综上，CUDA加速安装.bat需要修改为：
.\python.exe pip.pyz uninstall torch
.\python.exe pip.pyz install torch --index-url=https://download.pytorch.org/whl/cu118
PAUSE

**Comment by chn-lee-yumi** [comment]
> 文件内的几个需要调用python的bat脚本，路径使用了 ./python.exe ……，在win11环境运行会报错，可能win11需要强制使用反斜杠表示路径，应该改为 .\python.exe ……，修改后运行正常

这个问题我修复一下

> 安装cuda版本的bat脚本中并没有先卸载原有的torch

`install -U` 会强制更新，不需要进行卸载

**Comment by chn-lee-yumi** [comment]
新版本已修复
