### ISSUE TITLE
.env文件路径配置不生效

### ISSUE THREAD

**Issue by jianhudiyi** [chn-lee-yumi/MaterialSearch#79]
我在配置过一次路径并扫描后，下一次修改.env中的文件路径不生效，还是会扫描上一次的地址。文件已正常保存 ，在浏览器中也有刷新

具体报错是这样的，我第一次地址是：D:\影视\电影 正常扫描，第二次换：D:\影视\短剧 则会扫描上一次的文件，并且还会扫到D:\影视\综艺，没法一个个扫父级目录下的子文件夹。        
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/162315614/e8f4ab1b-b066-4988-900b-95fa26784694)

我的解决办法是：重新装了一遍，不放父级文件，然后这样扫描就正常了 D:\电影， D:\短剧， D:\综艺。

**Comment by chn-lee-yumi** [comment]
修改后需重启。

**Comment by jianhudiyi** [comment]
重启也不行

**Comment by chn-lee-yumi** [comment]
这个问题我有空尝试复现下

**Comment by chn-lee-yumi** [comment]
你是扫描完成后修改的路径，还是扫描到一半关了修改路径？

**Comment by jianhudiyi** [comment]
> 你是扫描完成后修改的路径，还是扫描到一半关了修改路径？

扫描完后更改的路径

**Comment by chn-lee-yumi** [comment]
我没有办法复现你的问题。如果可以的话，能否提供一个录屏展示一下过程？

**Comment by xsisiw** [comment]
> 我没有办法复现你的问题。如果可以的话，能否提供一个录屏展示一下过程？

我也遇到了，结果是因为自己运行了两次（重复运行），另一个窗口没有关闭，导致修改路径后还是那个窗口在处理

**Comment by xsisiw** [comment]
另外可以试试删除tmp\assets.pickle
