### ISSUE TITLE
运行install_torch_gpu.bat文件后，还是无法开启cuda加速

### ISSUE THREAD

**Issue by jianhudiyi** [chn-lee-yumi/MaterialSearch#81]
pip install -U torch --index-url=https://download.pytorch.org/whl/cu118
pause

up我在运行这行代码后，torch依旧没有安装成功，检查发现好像是安装到系统环境中去了，这个软件好像有个单独的环境（我也不是很懂程序这块，个人猜测），于是我查了下怎么在指定环境下安装包。以下是我的解决步骤：
1.我下载get-pip.py这个文件丢到了项目的根目录下。
2.然后再cmd中运行了这个python文件，python get-pip.py
3.用-m指定在该环境下安装torch，python -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

然后成功开启显卡加速了

**Comment by chn-lee-yumi** [comment]
你用的是整合包还是源码部署？

**Comment by KENUNK** [comment]
我也遇到同样的问题，按照这个哥们方法成功开启cuda加速，但是加速速度貌似不理想，gpu占用率0-5%左右，cuda占用率长期0%，10秒跳一次30%，显卡是nvdia 4070super 12G显存，也各种测试显卡环境cuda驱动都正常，可能某个参数可以更改是显卡使用率或者强度吧，不懂摸索中，感谢这位老哥的思路

**Comment by chn-lee-yumi** [comment]
> 加速速度貌似不理想，gpu占用率0-5%左右，cuda占用率长期0%，10秒跳一次30%

大概时间都花在了读取文件上面了吧，显卡不是瓶颈

**Comment by jianhudiyi** [comment]
> 你用的是整合包还是源码部署？

整合包

**Comment by chn-lee-yumi** [comment]
> > 你用的是整合包还是源码部署？
> 
> 整合包

整合包应该用`CUDA加速安装.bat`，而不是`install_torch_gpu.bat`

**Comment by jianhudiyi** [comment]
> > > 你用的是整合包还是源码部署？
> > 
> > 
> > 整合包
> 
> 整合包应该用，而不是，这个在使用说明里已经写了`CUDA加速安装.bat``install_torch_gpu.bat`

也没有用 我还是安装不上torch，都运行了

**Comment by chn-lee-yumi** [comment]
> 或许可以指定python解释器 例如：E:\MaterialSearchWindows\python.exe pip.pyz install torch --index-url=https://download.pytorch.org/whl/cu118 PAUSE 这样应该可以解决

不知道你用的是哪个版本的整合包，20240609的版本已经加了相对路径，能保证用的是整合包内自带的python

**Comment by freemedom** [comment]
“大概时间都花在了读取文件上面了吧，显卡不是瓶颈”
感觉逻辑实现有一些问题，

**Comment by chn-lee-yumi** [comment]
> 图片预处理实现有一些问题，没并行处理

试试调大BATCH_SIZE？

**Comment by freemedom** [comment]
https://github.com/huggingface/transformers/blob/a06a0d12636756352494b99b5b264ac9955bc735/src/transformers/models/chinese_clip/image_processing_chinese_clip.py#L285

@chn-lee-yumi 
这里可以看到，调大BATCH_SIZE，仍然是for循环顺序执行，没有并行。（查看任务管理器cpu占用也可以看到没跑满，只有10%左右）
而且BATCH_SIZE调的太大的话内存占用会非常高（由于to_numpy_array https://github.com/huggingface/transformers/blob/a06a0d12636756352494b99b5b264ac9955bc735/src/transformers/models/chinese_clip/image_processing_chinese_clip.py#L272）

**Comment by freemedom** [comment]
我现在大致写出来了一个多进程预处理的，不过还有一些小问题

**Comment by freemedom** [comment]
16*300=4800张图片
用原有的方式，笔记本4060，cuda加速，457.95257544517517秒
我改成4进程，cuda加速，158.19957447052002秒
理论上来说4进程这时候，gpu还没有完全利用

**Comment by freemedom** [comment]
64*300=19200张图片
427.7043721675873秒 这时gpu利用率大概30%，但是继续改进不太好搞了，暂时不折腾了
