### ISSUE TITLE
希望可以指定目录搜索，以及扫描建立索引时，用不同的数据库

### ISSUE THREAD

**Issue by try2020-code** [chn-lee-yumi/MaterialSearch#84]
另外说一下，图搜视频效果极差，我目前是把视频把帧保存成图片索引后，以图搜图效果就是100%好。 包括局部搜索都很好， 但目前是没法搜索指定视频的帧， 我所能想到的是把帧放到不同的目录。。但不支持这就是个很大的问题了

**Comment by chn-lee-yumi** [comment]
已列入TODO

**Comment by jianhudiyi** [comment]
图搜视频建议将值调到70~76附近，效果很好   如果是动作特别快的场景，去配置文件中可以改为一秒抽一帧，默认是两秒

**Comment by zuiaiyutu** [comment]
如果扫描的目录里包含很多视频，扫描需要花费几小时，时间太长了，要几个小时才能扫描完成。

**Comment by chn-lee-yumi** [comment]
刚刚更新的版本已添加路径筛选和修改时间范围筛选。你可以通过把对应的目录填到搜索路径里面，来达到你想要的效果。
