### ISSUE TITLE
我只想用以图搜图功能，怎样关闭chinese-clip的增加索引速度呢

### ISSUE THREAD

**Issue by try2020-code** [chn-lee-yumi/MaterialSearch#85]
也就是说。我目前只想用向量检测

**Comment by chn-lee-yumi** [comment]
没懂你在说什么。。。

**Comment by chn-lee-yumi** [comment]
> 就是不希望有chinese-clip 模型推理来实现以文搜图，我只用得到以图搜图。。

1. 这里用的不是chinese-clip模型，请看`config.py`
2. 索引速度无法提升，因为索引的不是你的输入，所以你用文字或者用图都是一样的

> 用的是什么向量数据库呢

没有用向量数据库
