### ISSUE TITLE
需求：上传图片后返回图片ID，通过图片ID来查询

### ISSUE THREAD

**Issue by Bule-lee** [chn-lee-yumi/MaterialSearch#87]
你好，  如果多个用户同时使用，如果在同一时间调用这个上传和搜索接口，这数据就乱了~

**Comment by Bule-lee** [comment]
你好，还有个问题， 就是用docker-compose 启动，然后再搜索，不如直接再windows上运行的查询准确率高，请问这个是和服务器分配的硬件资源有关还是 运行环境？

**Comment by chn-lee-yumi** [comment]
> 需求：上传图片后返回图片ID，通过图片ID来查询

 这个我没有做的打算，因为我没打算做多用户。如果你有兴趣，欢迎提交PR。
 
 > 就是用docker-compose 启动，然后再搜索，不如直接再windows上运行的查询准确率高
 
 按理说准确率应该一样的，因为都是用同一个模型，所以我也不知道为什么不一样。
