### ISSUE TITLE
能否加入批量图片搜视频功能啊；搜索出来的匹配片段能否指定数量，然后批量裁切下载

### ISSUE THREAD

**Issue by venusyob** [chn-lee-yumi/MaterialSearch#88]

**Comment by chn-lee-yumi** [comment]
不是很懂，能否详细说说？举个例子？

**Comment by venusyob** [comment]
应该是 基于用图片搜视频的方式，比如说批量导入图片，按照一定阈值找到视频，然后选择想要的视频片段，后批量按顺序导出；
1. 其中选择方式可手动选择，或者自动选择相似度最高的一个视频，
2. 导出方式可选择批量导出，或者合并为一个视频导出

**Comment by chn-lee-yumi** [comment]
这个功能有什么用？

**Comment by venusyob** [comment]
对于自媒体混剪找素材，日常积累素材，比如看见别人的作品中好的片段素材 截图在原片搜索，单个的效率太低，批量就是刚需

**Comment by chn-lee-yumi** [comment]
> 比如看见别人的作品中好的片段素材 截图在原片搜索，单个的效率太低，批量就是刚需

对于你说的这个场景，是不是看到好的素材，先截图，然后再下载原片，这样重复多次，然后执行扫描，最后把截好的一堆图拿去批量匹配。我的理解对吗？

**Comment by venusyob** [comment]
对，作者理解的通俗易懂，就是单张变多张图，感觉会影响页面展示

**Comment by venusyob** [comment]
![剪辑_看图王](https://github.com/chn-lee-yumi/MaterialSearch/assets/76506915/d155ab1d-307a-4919-9a46-ec4a1048f5ed)
这个视频时长裁剪功能的实现 感觉还可以——B站 人工智能小黄鸭
