### ISSUE TITLE
是否可以增加下载功能

### ISSUE THREAD

**Issue by yijun9988** [chn-lee-yumi/MaterialSearch#89]
能否增加下载与图片同名的压缩包的功能，素材里每个图片都有对应名称的压缩包（压缩包内是3D模型）
![微信图片_20240703165602](https://github.com/chn-lee-yumi/MaterialSearch/assets/168410258/0c72dac0-4338-4436-94f7-ee502ada3d35)

**Comment by chn-lee-yumi** [comment]
因为这个不是通用需求，所以我没打算做。
