### ISSUE TITLE
从搜索到的视频中下载匹配片段，前几秒缺帧

### ISSUE THREAD

**Issue by MindMeldMagus** [chn-lee-yumi/MaterialSearch#90]
https://github.com/chn-lee-yumi/MaterialSearch/assets/165874032/bcf09549-330f-429a-8657-027bc1ac5518

但凡超过了3秒就会有这种问题，是不是有帧率问题，前几秒卡的时候就像只有一帧一样

**Comment by chn-lee-yumi** [comment]
你好，能否上传原始视频，我测试一下？我手上的视频都没有这个问题。

**Comment by MindMeldMagus** [comment]
github只能上传10M以内的图片

这个是我的.env配置文件

**Comment by MindMeldMagus** [comment]
github视频最大只能上传10M   麻烦留一个邮箱我发一个过去

下面这个是我的.env配置文件
# 下面添加扫描路径，用逗号分隔
ASSETS_PATH=D:\sucai
# 下面填写扫描设备，cpu或cuda（cuda会使用NVIDIA显卡进行加速）。注意：N卡才能选cuda，并且请先运行"CUDA加速安装.bat"。
DEVICE=cuda
DEVICE_TEXT=cuda
# 下面的不要改
TRANSFORMERS_OFFLINE=1
HF_HOME=huggingface   

我用的是4090笔记本

**Comment by MindMeldMagus** [comment]
运行启动后的配置输出
********** 运行配置 / RUNNING CONFIGURATIONS **********
HOST: '0.0.0.0'
PORT: 8085
ASSETS_PATH: ('D:\\sucai',)
SKIP_PATH: ('/tmp',)
IMAGE_EXTENSIONS: ('.jpg', '.jpeg', '.png', '.gif', '.heic', '.webp', '.bmp')
VIDEO_EXTENSIONS: ('.mp4', '.flv', '.mov', '.mkv', '.webm', '.avi')
IGNORE_STRINGS: ('thumb', 'avatar', '__macosx', 'icons', 'cache')
FRAME_INTERVAL: 2
SCAN_PROCESS_BATCH_SIZE: 8
IMAGE_MIN_WIDTH: 64
IMAGE_MIN_HEIGHT: 64
AUTO_SCAN: False
AUTO_SCAN_START_TIME: (22, 30)
AUTO_SCAN_END_TIME: (8, 0)
AUTO_SAVE_INTERVAL: 100
MODEL_NAME: 'OFA-Sys/chinese-clip-vit-base-patch16'
DEVICE: 'cuda'
CACHE_SIZE: 64
POSITIVE_THRESHOLD: 36
NEGATIVE_THRESHOLD: 36
IMAGE_THRESHOLD: 85
LOG_LEVEL: 'INFO'
SQLALCHEMY_DATABASE_URL: 'sqlite:///./instance/assets.db'
TEMP_PATH: './tmp'
VIDEO_EXTENSION_LENGTH: 0
ENABLE_LOGIN: False
USERNAME: '83638'
PASSWORD: 'MaterialSearch'
FLASK_DEBUG: False
HF_HOME: huggingface
HF_HUB_OFFLINE: None
TRANSFORMERS_OFFLINE: 1
CWD: E:\Program Files (x86)\MaterialSearch
**************************************************
 * Serving Flask app 'main'
 * Debug mode: off
2024-07-05 09:10:59,154 werkzeug INFO WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8085
 * Running on http://192.168.50.215:8085
2024-07-05 09:10:59,154 werkzeug INFO Press CTRL+C to quit

**Comment by chn-lee-yumi** [comment]
> github视频最大只能上传10M 麻烦留一个邮箱我发一个过去

chn.lee.yumi@gmail.com

另外请说一下用的什么搜索词，我看看是不是剪出来一样的效果

**Comment by MindMeldMagus** [comment]
用的是 文字搜索视频   关键词   鞠躬

**Comment by MindMeldMagus** [comment]
我的视频素材在外置的SSD上，是通过笔记本type-c接的三星 970 EVO硬盘盒
邮件已经发送，原视频+搜索的关键词+结果截图

**Comment by chn-lee-yumi** [comment]
我可以复现你的问题。非常感谢你提供的问题，这个bug现在已修复。

**Comment by MindMeldMagus** [comment]
好的，那我现在可以单独替换bug修复文件就能得到解决吗？

**Comment by chn-lee-yumi** [comment]
> 那我现在可以单独替换bug修复文件就能得到解决吗？

是的，你把`utils.py`换掉就可以了。
