### ISSUE TITLE
关于网络图片进行扫描的

### ISSUE THREAD

**Issue by CZF39631** [chn-lee-yumi/MaterialSearch#91]
您好我看到您的代码里有涉及到关于从url建立特征的功能，不知道可不可以从URL建立数据库，而不从本地获取图片文件呢？
![微信图片_20240705154457](https://github.com/chn-lee-yumi/MaterialSearch/assets/136218631/8d892b37-3fc0-49f9-ba4a-9035ad1a14c3)

此外，能否不改动数据库，每次只做增量呢？

**Comment by CZF39631** [comment]
因为我需要从网络上获取图片并，这样的话，如果通过url建立数据库，那么我本地就不需要图片了，
但是如果还是以目前的从本地扫描的话，我这些图片如果删除了，或者因为某些原因丢失，那我就不能再重新进行扫描了，这会导致我扫描的时候，找不到这部分丢失的图片，对我来说图片的名字等信息比图片更重要，而图片只是为了让我能够进行查找的介质。

**Comment by chn-lee-yumi** [comment]
我没理解错的话，你的意思就是想通过提供一堆图片url来进行扫描？

**Comment by CZF39631** [comment]
是的，这些图片URL和图片名我已经用了数据库存储了，我这边也在看您的代码，看我有没有希望实现通过url扫描入库的功能

**Comment by chn-lee-yumi** [comment]
这个功能在TODO List里面。不过最近我不会去做。如果你急需，可以自己修改代码。

**Comment by CZF39631** [comment]
好的，
