### ISSUE TITLE
请求增加更多gpu加速方式

### ISSUE THREAD

**Issue by Lugic1993** [chn-lee-yumi/MaterialSearch#92]
大佬，请求docker版本增加更多gpu加速方式，比如说intel显卡（例如dg1等）
现有的cpu/cuda/mps都驱动不了，也不知道
devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [ gpu ]
这里应该怎么改nvidia值

**Comment by Lugic1993** [comment]
非常感谢做的这个项目，非常好用！效果非常赞！膜拜一下

**Comment by chn-lee-yumi** [comment]
把#删掉就表示用n卡。什么也不改就是cpu。其它的我也没有办法支持。
