### ISSUE TITLE
麻烦问下 pexels视频从哪里来的怎么扫描的，目前不能下载视频，我想更新视频下载地址

### ISSUE THREAD

**Issue by openainext** [chn-lee-yumi/MaterialSearch#94]
麻烦问下 pexels视频从哪里来的怎么扫描的，目前不能下载

**Comment by chn-lee-yumi** [comment]
请见：https://github.com/chn-lee-yumi/MaterialSearch/blob/main/process_pexels.py

**Comment by openainext** [comment]
404 找不到这个文件

**Comment by openainext** [comment]
pexels 原始视频 能共享下吗

**Comment by chn-lee-yumi** [comment]
目前确实视频都过期了。我暂时去掉了这个功能。后续有空再搞搞。
