### ISSUE TITLE
十万张图索引后加入索引速度下降

### ISSUE THREAD

**Issue by xsisiw** [chn-lee-yumi/MaterialSearch#95]
一开始很快一秒很多个，但是录入的图片多了后感觉是sqlite的性能下降了一秒只有两个，如果用mysql是不是会好一些，我的一个项目用mysql索引了千万图片的md5，发现mysql 的性能会很好几乎不会影响录入速度

**Comment by chn-lee-yumi** [comment]
你可以尝试改一下代码用mysql？看看效果如何

**Comment by chn-lee-yumi** [comment]
改这里应该就可以了：https://github.com/chn-lee-yumi/MaterialSearch/blob/main/models.py

**Comment by xsisiw** [comment]
> 改这里应该就可以了：https://github.com/chn-lee-yumi/MaterialSearch/blob/main/models.py

谢谢，我以为要改一大堆，没想到就改这个文件和config，已经改成mysql的并且测试可以用了，我录入几百万张图片试试效果

**Comment by xsisiw** [comment]
测了下
SQLITE  193秒 5603张图，数据库占用空间23MB
MYSQL 178秒 5603张图，数据库占用空间11MB
意料之内的提升了性能和缩减了数据库大小，不过还没测试几百万张图的性能

**Comment by chn-lee-yumi** [comment]
> 可能是mysql我设置的索引只有255的长度搜索会慢一秒

试试删掉索引重建一个？

**Comment by chn-lee-yumi** [comment]
> 可能是mysql我设置的索引只有255的长度搜索会慢一秒

改下索引试试？

**Comment by xsisiw** [comment]
> 改下索引试试？

path的索引最多250，没有办法增加了，但是搜索的话都是全表搜索features这个的，所以path的索引应该不影响搜索速度的，MYSQL应该可以用redis等缓存把数据放到内存里面不用频繁的读取磁盘内容应该可以加速，这个我再研究研究，据说sqlite是直接读取数据可能要比使用服务的mysql更快一些吧，自己也不是很熟悉

**Comment by chn-lee-yumi** [comment]
搜索是features这个向量的距离计算。改用向量数据库可能会好一些，但是我没有空测，估计代码也得大改。
