### ISSUE TITLE
我发现文搜图使用英文逗号分隔关键词匹配的结果会更准确

### ISSUE THREAD

**Issue by xsisiw** [chn-lee-yumi/MaterialSearch#96]
英文逗号，空格 ，自然语言，中文逗号，逗号+空格 都试了下，只有英文逗号分隔关键词的方式会更精确找到需要的结果，直接在前三张，其他方式（空格 ，自然语言，中文逗号）搜到的目标图片都排在6张以后了，优化的话建议在前端或者后端替换用户输入的中文逗号、空格为英文逗号这样会更准确

**Comment by chn-lee-yumi** [comment]
在前端加一句提示可能更方便2333

**Comment by chn-lee-yumi** [comment]
你的英文逗号后面会接一个空格吗？

**Comment by xsisiw** [comment]
> 你的英文逗号后面会接一个空格吗？

实测逗号加空格不影响结果

**Comment by chn-lee-yumi** [comment]
最新的commit已在前端添加提示。
