### ISSUE TITLE
扫描不完就出错

### ISSUE THREAD

**Issue by hnjyzzy** [chn-lee-yumi/MaterialSearch#97]
Unused or unrecognized kwargs: padding.扫描不完就出错

**Comment by chn-lee-yumi** [comment]
截图？

**Comment by hnjyzzy** [comment]
![1](https://github.com/user-attachments/assets/335da82b-1cd1-454d-9497-2a90654ec78f)

**Comment by hnjyzzy** [comment]
![2](https://github.com/user-attachments/assets/66124912-ced2-42cf-a104-d83b5220c516)

**Comment by chn-lee-yumi** [comment]
你这个截图，并没有显示你之前的报错（Unused or unrecognized kwargs: padding）啊？

**Comment by hnjyzzy** [comment]
那是下载另外一个整合包出现的问题，用你的整合包出现的是截图上的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月17日(周三) 上午8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chn-lee-yumi/MaterialSearch] 扫描不完就出错 (Issue #97)




 
你这个截图，并没有显示你之前的报错（Unused or unrecognized kwargs: padding）啊？

**Comment by chn-lee-yumi** [comment]
能否将复现过程录屏发我邮箱？chn.lee.yumi@gmail.com

**Comment by chn-lee-yumi** [comment]
已收到你的邮件，我看了下，确实是个很奇怪的问题……

**Comment by chn-lee-yumi** [comment]
我现在没什么头绪，因为代码没有任何报错就突然退出了，但是代码里并没有任何直接退出的逻辑。想问下你电脑内存多大？我只能推荐换台电脑试试了……

**Comment by chn-lee-yumi** [comment]
你的CPU太老了，可能不支持新的指令集（AVX），导致崩溃。只是个人猜测。。。

**Comment by hnjyzzy** [comment]
我用别的电脑试了一下，就是我电脑的问题，有什么办法解决一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chn-lee-yumi/MaterialSearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chn-lee-yumi/MaterialSearch] 扫描不完就出错 (Issue #97)





 
你的CPU太老了，可能不支持新的指令集（AVX），导致崩溃。只是个人猜测。。。
