### ISSUE TITLE
关于大批量图片无法搜到图片的问题

### ISSUE THREAD

**Issue by CZF39631** [chn-lee-yumi/MaterialSearch#99]
我在使用过程中遇到一个情况，搜图片搜索不到，但是因为我有命名习惯，所以都重新命名了，我几乎用的原图去搜索我想要的图，但是尝试失败了，搜索不到那个图，同时我尝试了提高搜索图的分辨率，以及截取不同部分，进行搜索，都无法很好的都到这个图片，目前图片库拥有23W张图

**Comment by CZF39631** [comment]
我确定是有的，因为我用文件名搜到了这个图

**Comment by chn-lee-yumi** [comment]
能否把你的过程录屏发送到我的邮箱？chn.lee.yumi@gmail.com

包括原图长什么样，用文件名能搜出来，以及原图搜不出来等等

**Comment by chn-lee-yumi** [comment]
我还没收到你的录屏，请问你发了吗？

**Comment by CZF39631** [comment]
暂时还没有复现这个图片，但是上周出现了两例，我后来去处理的时候忘记记录那两张图片了，如果有必要我可以先结了这个issues，复现这个问题再给您发送？

**Comment by chn-lee-yumi** [comment]
> 暂时还没有复现这个图片，但是上周出现了两例，我后来去处理的时候忘记记录那两张图片了，如果有必要我可以先结了这个issues，复现这个问题再给您发送？

没问题

**Comment by CZF39631** [comment]
好的没问题
